services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: WarframeRivens
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1234qwerQ!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - WarframeRivens
    restart: unless-stopped
networks:
  WarframeRivens:
    name: WarframeRivens
volumes:
  sql_data: