// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarframeRivensAPI.Data;

#nullable disable

namespace WarframeRivensAPI.Migrations.WarRiven
{
    [DbContext(typeof(WarRivenContext))]
    [Migration("20250514122315_InitRivens")]
    partial class InitRivens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WarframeRivensAPI.Models.Favorito", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdRiven")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RivenId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.HasIndex("RivenId");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("WarframeRivensAPI.Models.Oferta", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Destino")
                        .HasColumnType("bit");

                    b.Property<bool>("Disponibilidad")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdComprador")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdRiven")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Partida")
                        .HasColumnType("bit");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RivenId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdComprador");

                    b.HasIndex("RivenId");

                    b.ToTable("Ofertas");
                });

            modelBuilder.Entity("WarframeRivensAPI.Models.Riven", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Arma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Atrib1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Atrib2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Atrib3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAtrib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DValor")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("IdPropietario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor1")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("Valor2")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("Valor3")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("IdPropietario");

                    b.ToTable("Rivens");
                });

            modelBuilder.Entity("WarframeRivensAPI.Models.Venta", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdComprador")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdRiven")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdVendedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RivenId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdComprador");

                    b.HasIndex("IdVendedor");

                    b.HasIndex("RivenId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("WarframeRivensAPI.Models.WarUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Icono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SteamId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarframeNick")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WarUser");
                });

            modelBuilder.Entity("WarframeRivensAPI.Models.Favorito", b =>
                {
                    b.HasOne("WarframeRivensAPI.Models.WarUser", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarframeRivensAPI.Models.Riven", "Riven")
                        .WithMany()
                        .HasForeignKey("RivenId");

                    b.Navigation("Riven");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WarframeRivensAPI.Models.Oferta", b =>
                {
                    b.HasOne("WarframeRivensAPI.Models.WarUser", "Comprador")
                        .WithMany()
                        .HasForeignKey("IdComprador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarframeRivensAPI.Models.Riven", "Riven")
                        .WithMany()
                        .HasForeignKey("RivenId");

                    b.Navigation("Comprador");

                    b.Navigation("Riven");
                });

            modelBuilder.Entity("WarframeRivensAPI.Models.Riven", b =>
                {
                    b.HasOne("WarframeRivensAPI.Models.WarUser", "Propietario")
                        .WithMany()
                        .HasForeignKey("IdPropietario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("WarframeRivensAPI.Models.Venta", b =>
                {
                    b.HasOne("WarframeRivensAPI.Models.WarUser", "Comprador")
                        .WithMany()
                        .HasForeignKey("IdComprador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarframeRivensAPI.Models.WarUser", "Vendedor")
                        .WithMany()
                        .HasForeignKey("IdVendedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarframeRivensAPI.Models.Riven", "Riven")
                        .WithMany()
                        .HasForeignKey("RivenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Riven");

                    b.Navigation("Vendedor");
                });
#pragma warning restore 612, 618
        }
    }
}
