use WarframeRivens
go

INSERT INTO Rivens ( Id,Arma, Nombre, IdPropietario, Atrib1, Valor1, Atrib2, Valor2, Atrib3, Valor3, DAtrib, DValor, Polaridad, Maestria) VALUES 
(NEWID(),'Amprex', 'Critacan', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 193.3, 'Multishot', 111.7, NULL, NULL, 'Infested Damage', -21.6, 'madurai', 8),
(NEWID(),'Amprex', 'Crita-visimag', 'CambiarEstoPorIdDeAdmin', 'Weapon Recoil', -61.0, 'Critical Chance', 114.5, 'Damage', 121.6, NULL, NULL, 'vazarin', 8),
(NEWID(),'Amprex', 'Herapha', 'CambiarEstoPorIdDeAdmin', 'Zoom', 77.0, 'Heat Damage', 112.4, NULL, NULL, 'Fire Rate', -28.4, 'vazarin', 10),
(NEWID(),'Amprex', 'Ampitis', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 109.4, 'Ammo maximum', 49.7, NULL, NULL, NULL, NULL, 'vazarin', 10),
(NEWID(),'Amprex', 'Acri-visitin', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 98.4, 'Damage', 132.7, 'Magazine Capacity', 34.7, NULL, NULL, 'madurai', 11),
(NEWID(),'Amprex', 'Acri-Toxinron', 'CambiarEstoPorIdDeAdmin', 'Toxin Damage', 67.0, 'Critical Damage', 95.5, 'Critical Chance', 109.8, NULL, NULL, 'naramon', 11),
(NEWID(),'Amprex', 'Toxi-visitron', 'CambiarEstoPorIdDeAdmin', 'Toxin Damage', 67.6, 'Corpus Damage', 29.5, 'Damage', 111.6, NULL, NULL, 'naramon', 11),
(NEWID(),'Amprex', 'Acri-heranok', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 108.5, 'Zoom', 51.5, 'Punch Through', 210.0, 'Ammo Maximum', -33.1, 'vazarin', 12),
(NEWID(),'Amprex', 'Critalpha', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 155.7, 'Heat Damage', 84.3, NULL, NULL, NULL, NULL, 'naramon', 12),
(NEWID(),'Amprex', 'Lexicron', 'CambiarEstoPorIdDeAdmin', 'Punch Through', 320.0, 'Critical Chance', 179.9, NULL, NULL, 'Ammo maximum', -22.5, 'vazarin', 13),
(NEWID(),'Amprex', 'Visican', 'CambiarEstoPorIdDeAdmin', 'Multishot', 98.1, 'Damage', 214.3, NULL, NULL, 'Status Chance', -41.6, 'vazarin', 13),
(NEWID(),'Amprex', 'Critaata', 'CambiarEstoPorIdDeAdmin', 'Damage', 180.0, 'Critical Chance', 165.3, NULL, NULL, 'Critical Damage', -59.1, 'madurai', 14),
(NEWID(),'Amprex', 'Toxitron', 'CambiarEstoPorIdDeAdmin', 'Corpus Damage', 50.1, 'Toxin Damage', 114.8, NULL, NULL, 'Infested Damage', -22.8, 'vazarin', 15),
(NEWID(),'Amprex', 'Toxibin', 'CambiarEstoPorIdDeAdmin', 'Ammo maximum', 46.6, 'Toxin Damage', 87.1, NULL, NULL, NULL, NULL, 'vazarin', 16),
(NEWID(),'Attica', 'Satipha', 'CambiarEstoPorIdDeAdmin', 'Multishot', 126.1, 'Heat Damage', 106.4, NULL, NULL, NULL, NULL, 'naramon', 8),
(NEWID(),'Attica', 'Critacak', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 251.0, 'Puncture Damage', 194.1, NULL, NULL, 'Fire Rate', -38.4, 'naramon', 11),
(NEWID(),'Attica', 'Critatis', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 264.8, 'Critical Damage', 194.7, NULL, NULL, 'Puncture Damage', -85.7, 'madurai', 11),
(NEWID(),'Attica', 'Visi-Armacron', 'CambiarEstoPorIdDeAdmin', 'Magazine Capacity', 62.3, 'Damage', 211.1, 'Critical Chance', 186.1, 'Fire Rate', -64.1, 'madurai', 12),
(NEWID(),'Attica', 'Visi-critatox', 'CambiarEstoPorIdDeAdmin', 'Damage', 177.2, 'Toxin Damage', 82.0, 'Critical Chance', 146.4, NULL, NULL, 'vazarin', 12),
(NEWID(),'Attica', 'Saticron', 'CambiarEstoPorIdDeAdmin', 'Multishot', 144.7, 'Critical Chance', 223.6, NULL, NULL, 'Reload Speed', -29.6, 'madurai', 13),
(NEWID(),'Attica', 'Feva-igniata', 'CambiarEstoPorIdDeAdmin', 'Reload Speed', 51.7, 'Damage', 166.5, 'Heat Damage', 92.4, NULL, NULL, 'madurai', 14),
(NEWID(),'Attica', 'Visinok', 'CambiarEstoPorIdDeAdmin', 'Damage', 235.4, 'Punch Through', 330.0, NULL, NULL, NULL, NULL, 'naramon', 16),
(NEWID(),'Boltor', 'Visitin-critacon', 'CambiarEstoPorIdDeAdmin', 'Damage', 171.1, 'Magazine Capacity', 46.4, NULL, NULL, 'Corpus Damage', -16.7, 'vazarin', 10),
(NEWID(),'Boltor', 'Critado', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 144.2, 'Cold Damage', 85.9, NULL, NULL, 'Multishot', -35.2, 'vazarin', 13),
(NEWID(),'Boltor', 'Conci-Acrides', 'CambiarEstoPorIdDeAdmin', 'Flight Speed', 72.1, 'Status Duration', 78.5, 'Critical Damage', 95.3, 'Magazine Capacity', -29.4, 'vazarin', 14),
(NEWID(),'Boltor', 'Visi-saticron', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 111.4, 'Multishot', 67.7, 'Damage', 130.2, 'Critical Damage', -67.2, 'madurai', 15),
(NEWID(),'Boltor', 'Acripha', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 64.5, 'Critical Damage', 91.1, NULL, NULL, NULL, NULL, 'madurai', 16),
(NEWID(),'Boltor', 'Visi-ignilis', 'CambiarEstoPorIdDeAdmin', 'Zoom', 32.2, 'Damage', 102.2, 'Heat Damage', 50.6, NULL, NULL, 'naramon', 16),
(NEWID(),'Braton', 'Vexiata', 'CambiarEstoPorIdDeAdmin', 'Damage', 143.8, 'Electric Damage', 81.0, NULL, NULL, NULL, NULL, 'madurai', 8),
(NEWID(),'Braton', 'Acri-satatin', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 116.1, 'Magazine Capacity', 42.1, 'Multishot', 84.2, 'Status Duration', -79.0, 'vazarin', 12),
(NEWID(),'Braton', 'Vexi-scimag', 'CambiarEstoPorIdDeAdmin', 'Electric Damage', 70.3, 'Weapon Recoil', -62.2, 'Slash Damage', 87.5, NULL, NULL, 'naramon', 14),
(NEWID(),'Braton', 'Puratin', 'CambiarEstoPorIdDeAdmin', 'Infested Damage', 44.4, 'Magazine Capacity', 47.3, NULL, NULL, NULL, NULL, 'naramon', 14),
(NEWID(),'Braton', 'Zeti-satiada', 'CambiarEstoPorIdDeAdmin', 'Infested Damage', 31.2, 'Weapon Recoil', -69.8, 'Multishot', 63.5, NULL, NULL, 'vazarin', 15),
(NEWID(),'Braton', 'Ampitox', 'CambiarEstoPorIdDeAdmin', 'Ammo maximum', 51.4, 'Toxin Damage', 84.0, NULL, NULL, NULL, NULL, 'naramon', 14),
(NEWID(),'Burston', 'Cronidex', 'CambiarEstoPorIdDeAdmin', 'Status Chance', 136.9, 'Fire Rate', 93.4, NULL, NULL, 'Ammo maximum', -27.9, 'naramon', 8),
(NEWID(),'Burston', 'Igni-Vexitak', 'CambiarEstoPorIdDeAdmin', 'Reload Speed', 53.5, 'Heat Damage', 105.3, 'Electric Damage', 97.4, 'Fire Rate', -56.3, 'vazarin', 10),
(NEWID(),'Burston', 'Feva-ignicron', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 152.7, 'Heat Damage', 97.2, 'Reload Speed', 56.6, 'Damage', -153.2, 'vazarin', 13),
(NEWID(),'Burston', 'Lexido', 'CambiarEstoPorIdDeAdmin', 'Cold Damage', 131.4, 'Punch Through', 370.0, NULL, NULL, 'Magazine Capacity', -30.9, 'naramon', 16),
(NEWID(),'Buzlok', 'Critican', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 279.9, 'Multishot', 149.1, NULL, NULL, 'Weapon Recoil', 54.3, 'vazarin', 11),
(NEWID(),'Buzlok', 'Igni-satinak', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 101.6, 'Multishot', 100.2, 'Flight Speed', 99.8, NULL, NULL, 'vazarin', 11),
(NEWID(),'Buzlok', 'Decitox', 'CambiarEstoPorIdDeAdmin', 'Toxin Damage', 114.9, 'Status Duration', 129.6, NULL, NULL, NULL, NULL, 'naramon', 11),
(NEWID(),'Buzlok', 'Cronitron', 'CambiarEstoPorIdDeAdmin', 'Fire Rate', 113.1, 'Corpus Damage', 76.2, NULL, NULL, 'Status Chance', -60.7, 'madurai', 16),
(NEWID(),'Cernos', 'Scican', 'CambiarEstoPorIdDeAdmin', 'Multishot', 89.5, 'Slash Damage', 123.1, NULL, NULL, 'Grineer Damage', -20.1, 'naramon', 13),
(NEWID(),'Cernos', 'Conci-acrido', 'CambiarEstoPorIdDeAdmin', 'Cold Damage', 53.8, 'Critical Damage', 82.1, 'Flight Speed', 61.8, NULL, NULL, 'vazarin', 14),
(NEWID(),'Cernos', 'Zeti-vexican', 'CambiarEstoPorIdDeAdmin', 'Weapon Recoil', -63.2, 'Multishot', 55.2, 'Electric Damage', 59.0, NULL, NULL, 'naramon', 16),
(NEWID(),'Daikyu', 'Argido', 'CambiarEstoPorIdDeAdmin', 'Grineer Damage', 69.8, 'Cold Damage', 121.4, NULL, NULL, 'Multishot', -53.2, 'naramon', 8),
(NEWID(),'Daikyu', 'Insi-Puraton', 'CambiarEstoPorIdDeAdmin', 'Puncture Damage', 117.1, 'Infested Damage', 43.1, 'Impact Damage', 98.2, NULL, NULL, 'vazarin', 10),
(NEWID(),'Daikyu', 'Mantibin', 'CambiarEstoPorIdDeAdmin', 'Corpus Damage', 58.0, 'Ammo maximum', 63.5, NULL, NULL, NULL, NULL, 'vazarin', 11),
(NEWID(),'Daikyu', 'Insi-visitox', 'CambiarEstoPorIdDeAdmin', 'Puncture Damage', 142.4, 'Toxin Damage', 97.4, 'Damage', 192.5, 'Critical Damage', -101.6, 'naramon', 11),
(NEWID(),'Daikyu', 'Gelicron', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 173.8, 'Cold Damage', 109.5, NULL, NULL, NULL, NULL, 'vazarin', 14),
(NEWID(),'Daikyu', 'Visi-hexades', 'CambiarEstoPorIdDeAdmin', 'Status Duration', 108.7, 'Damage', 198.0, 'Status Chance', 101.6, 'Puncture Damage', -100.8, 'madurai', 15),
(NEWID(),'Daikyu', 'Sati-ampicak', 'CambiarEstoPorIdDeAdmin', 'Puncture Damage', 102.2, 'Multishot', 86.8, 'Ammo maximum', 48.1, NULL, NULL, 'madurai', 15),
(NEWID(),'Daikyu', 'Zetiata', 'CambiarEstoPorIdDeAdmin', 'Weapon Recoil', -116.7, 'Damage', 179.8, NULL, NULL, NULL, NULL, 'madurai', 15),
(NEWID(),'Daikyu', 'Hexacron', 'CambiarEstoPorIdDeAdmin', 'Status Chance', 114.2, 'Critical Chance', 211.4, NULL, NULL, 'Damage', -94.5, 'vazarin', 16),
(NEWID(),'Dera', 'Heracron', 'CambiarEstoPorIdDeAdmin', 'Zoom', 75.5, 'Critical Chance', 175.7, NULL, NULL, NULL, NULL, 'naramon', 11),
(NEWID(),'Dera', 'Mantiata', 'CambiarEstoPorIdDeAdmin', 'Corpus Damage', 60.6, 'Damage', 195.8, NULL, NULL, NULL, NULL, 'vazarin', 13),
(NEWID(),'Dera', 'Armacan', 'CambiarEstoPorIdDeAdmin', 'Multishot', 106.7, 'Magazine Capacity', 66.0, NULL, NULL, NULL, NULL, 'madurai', 13),
(NEWID(),'Dera', 'Argi-visicak', 'CambiarEstoPorIdDeAdmin', 'Damage', 192.2, 'Puncture Damage', 126.3, 'Grineer Damage', 52.6, 'Reload Speed', -51.3, 'naramon', 16),
(NEWID(),'Deth Machine Rifle', 'Pura-ampidra', 'CambiarEstoPorIdDeAdmin', 'Infested Damage', 63.2, 'Fire Rate', 79.5, 'Ammo maximum', 70.2, 'Critical Damage', 142.9, 'naramon', 12),
(NEWID(),'Deth Machine Rifle', 'Croni-Satiata', 'CambiarEstoPorIdDeAdmin', 'Damage', 220.4, 'Multishot', 128.8, 'Fire Rate', 88.3, 'Zoom', -64.5, 'madurai', 10),
(NEWID(),'Deth Machine Rifle', 'Ampimag', 'CambiarEstoPorIdDeAdmin', 'Weapon Recoil', -177.9, 'Ammo maximum', 98.9, NULL, NULL, 'Status Chance', -59.8, 'naramon', 14),
(NEWID(),'Dread', 'Acriata', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 124.2, 'Damage', 162.2, NULL, NULL, 'Ammo maximum', -19.9, 'madurai', 8),
(NEWID(),'Dread', 'Ampitio', 'CambiarEstoPorIdDeAdmin', 'Electric Damage', 90.0, 'Ammo maximum', 53.8, NULL, NULL, 'Critical Chance', -55.7, 'madurai', 8),
(NEWID(),'Dread', 'Igni-puratox', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 69.4, 'Infested Damage', 33.7, 'Toxin Damage', 64.4, 'Grineer Damage', -25.1, 'naramon', 8),
(NEWID(),'Dread', 'Conci-insicon', 'CambiarEstoPorIdDeAdmin', 'Flight Speed', 53.7, 'Puncture Damage', 68.6, 'Grineer Damage', 25.3, NULL, NULL, 'naramon', 8),
(NEWID(),'Dread', 'Acri-ignican', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 70.6, 'Multishot', 64.3, 'Critical Damage', 100.1, 'Impact Damage', -76.5, 'madurai', 9),
(NEWID(),'Dread', 'Zetinak', 'CambiarEstoPorIdDeAdmin', 'Weapon Recoil', -78.3, 'Flight Speed', 70.6, NULL, NULL, NULL, NULL, 'madurai', 13),
(NEWID(),'Dread', 'Critapha', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 84.8, 'Critical Chance', 141.9, NULL, NULL, 'Infested Damage', -17.3, 'madurai', 15),
(NEWID(),'Dread', 'Magna-Visicak', 'CambiarEstoPorIdDeAdmin', 'Puncture Damage', 84.4, 'Damage', 130.3, 'Impact Damage', 96.3, 'Weapon Recoil', 52.3, 'madurai', 15),
(NEWID(),'Dread', 'Lexitis', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 90.9, 'Punch Through', 2.0, NULL, NULL, NULL, NULL, 'madurai', 15),
(NEWID(),'Dread', 'Crita-acritio', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 96.2, 'Critical Damage', 76.1, 'Electric Damage', 51.3, NULL, NULL, 'madurai', 15),
(NEWID(),'Dread', 'Visi-satitak', 'CambiarEstoPorIdDeAdmin', 'Reload Speed', 27.9, 'Damage', 110.9, 'Multishot', 59.1, NULL, NULL, 'madurai', 15),
(NEWID(),'Dread', 'Acri-zetitak', 'CambiarEstoPorIdDeAdmin', 'Reload Speed', 28.2, 'Weapon Recoil', -53.8, 'Critical Damage', 78.5, NULL, NULL, 'madurai', 13),
(NEWID(),'Flux Rifle', 'Hexasus', 'CambiarEstoPorIdDeAdmin', 'Status Chance', 167.1, 'Slash Damage', 197.4, NULL, NULL, 'Ammo maximum', -33.6, 'vazarin', 13),
(NEWID(),'Flux Rifle', 'Toxitis', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 162.3, 'Toxin Damage', 131.8, NULL, NULL, NULL, NULL, 'naramon', 15),
(NEWID(),'Flux Rifle', 'Visi-mantibin', 'CambiarEstoPorIdDeAdmin', 'Damage', 172.8, 'Ammo maximum', 46.8, 'Corpus Damage', 43.2, NULL, NULL, 'naramon', 15),
(NEWID(),'Flux Rifle', 'Visides', 'CambiarEstoPorIdDeAdmin', 'Damage', 240.6, 'Status Duration', 140.5, NULL, NULL, NULL, NULL, 'vazarin', 15),
(NEWID(),'Flux Rifle', 'Sati-argitak', 'CambiarEstoPorIdDeAdmin', 'Grineer Damage', 50.1, 'Reload Speed', 51.9, 'Multishot', 100.9, NULL, NULL, 'naramon', 15),
(NEWID(),'Flux Rifle', 'Toxidex', 'CambiarEstoPorIdDeAdmin', 'Status Chance', 141.1, 'Toxin Damage', 164.9, NULL, NULL, 'Reload Speed', -35.3, 'madurai', 16),
(NEWID(),'Flux Rifle', 'Lexi-ignides', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 119.1, 'Punch Through', 350.0, 'Status Duration', 126.2, 'Status Chance', -84.4, 'madurai', 16),
(NEWID(),'Flux Rifle', 'Acri-ampicron', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 149.7, 'Ammo maximum', 49.9, 'Critical Damage', 122.6, NULL, NULL, 'naramon', 16),
(NEWID(),'Flux Rifle', 'Zetinok', 'CambiarEstoPorIdDeAdmin', 'Punch Through', 350.0, 'Weapon Recoil', -126.0, NULL, NULL, NULL, NULL, 'vazarin', 16),
(NEWID(),'Flux Rifle', 'Acriata', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 222.3, 'Damage', 263.1, NULL, NULL, 'Fire Rate', -39.1, 'madurai', 16),
(NEWID(),'Flux Rifle', 'Hexa-ampitis', 'CambiarEstoPorIdDeAdmin', 'Ammo maximum', 62.6, 'Status Chance', 120.9, 'Critical Damage', 146.8, 'Slash Damage', -135.0, 'madurai', 16),
(NEWID(),'Flux Rifle', 'Lexi-ampiata', 'CambiarEstoPorIdDeAdmin', 'Ammo maximum', 65.3, 'Damage', 214.9, 'Punch Through', 3.3, 'Fire Rate', -58.0, 'naramon', 16),
(NEWID(),'Flux Rifle', 'Toxitio', 'CambiarEstoPorIdDeAdmin', 'Toxin Damage', 119.6, 'Electric Damage', NULL, NULL, NULL, NULL, NULL, 'vazarin', 16),
(NEWID(),'Glaxion', 'Zeti-cronitin', 'CambiarEstoPorIdDeAdmin', 'Magazine Capacity', 59.4, 'Fire Rate', 73.2, 'Weapon Recoil', -115.6, 'Critical Chance', -154.6, 'naramon', 15),
(NEWID(),'Glaxion', 'Mantiada', 'CambiarEstoPorIdDeAdmin', 'Corpus Damage', 71.9, 'Infested Damage', 68.6, NULL, NULL, 'Grineer Damage', -29.8, 'naramon', 15),
(NEWID(),'Glaxion', 'Ampidex', 'CambiarEstoPorIdDeAdmin', 'Ammo maximum', 66.6, 'Status Chance', 118.6, NULL, NULL, NULL, NULL, 'naramon', 15),
(NEWID(),'Glaxion', 'Mantipha', 'CambiarEstoPorIdDeAdmin', 'Corpus Damage', 65.5, 'Heat Damage', 130.9, NULL, NULL, NULL, NULL, 'madurai', 15),
(NEWID(),'Glaxion', 'Hexa-vexitron', 'CambiarEstoPorIdDeAdmin', 'Electric Damage', 93.3, 'Status Chance', 95.2, 'Corpus Damage', 45.3, NULL, NULL, 'naramon', 15),
(NEWID(),'Glaxion', 'Crita-fevacan', 'CambiarEstoPorIdDeAdmin', 'Multishot', 114.2, 'Reload Speed', 65.4, 'Critical Chance', 203.6, 'Critical Damage', -111.2, 'madurai', 16),
(NEWID(),'Glaxion', 'Argitox', 'CambiarEstoPorIdDeAdmin', 'Toxin Damage', 162.3, 'Grineer Damage', 81.9, NULL, NULL, 'Reload Speed', -33.3, 'naramon', 10),
(NEWID(),'Gorgon', 'Deci-argitin', 'CambiarEstoPorIdDeAdmin', 'Grineer Damage', 46.9, 'Magazine Capacity', 50.6, 'Status Duration', 114.6, 'Multishot', -86.2, 'madurai', 9),
(NEWID(),'Gorgon', 'Igniton', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 142.8, 'Impact Damage', 163.2, NULL, NULL, 'Multishot', -50.9, 'madurai', 9),
(NEWID(),'Gorgon', 'Purado', 'CambiarEstoPorIdDeAdmin', 'Cold Damage', 97.0, 'Infested Damage', 54.1, NULL, NULL, NULL, NULL, 'madurai', 9),
(NEWID(),'Gorgon', 'Sati-critamag', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 136.4, 'Weapon Recoil', -74.1, 'Multishot', 85.5, NULL, NULL, 'madurai', 9),
(NEWID(),'Gorgon', 'Ignicon', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 111.5, 'Grineer Damage', 47.3, NULL, NULL, NULL, NULL, 'madurai', 9),
(NEWID(),'Gorgon', 'Lexipha', 'CambiarEstoPorIdDeAdmin', 'Punch Through', 290.0, 'Heat Damage', 100.3, NULL, NULL, NULL, NULL, 'madurai', 9),
(NEWID(),'Gorgon', 'Magna-Armades', 'CambiarEstoPorIdDeAdmin', 'Magazine Capacity', 56.8, 'Impact Damage', 141.8, 'Status Duration', 103.5, 'Weapon Recoil', 73.1, 'vazarin', 14),
(NEWID(),'Gorgon', 'Puratio', 'CambiarEstoPorIdDeAdmin', 'Infested Damage', 56.3, 'Electric Damage', 110.8, NULL, NULL, NULL, NULL, 'madurai', 15),
(NEWID(),'Gorgon', 'Magnaata', 'CambiarEstoPorIdDeAdmin', 'Impact Damage', 138.6, 'Damage', 184.5, NULL, NULL, NULL, NULL, 'vazarin', 16),
(NEWID(),'Grakata', 'Mantiada', 'CambiarEstoPorIdDeAdmin', 'Corpus Damage', 63.5, 'Infested Damage', 56.9, NULL, NULL, 'Critical Damage', -68.7, 'naramon', 11),
(NEWID(),'Grakata', 'Armaata', 'CambiarEstoPorIdDeAdmin', 'Magazine Capacity', 71.9, 'Damage', 230.5, NULL, NULL, 'Status Chance', -44.5, 'madurai', 14),
(NEWID(),'Grakata', 'Fevanok', 'CambiarEstoPorIdDeAdmin', 'Reload Speed', 70.6, 'Punch Through', 3.4, NULL, NULL, 'Status Duration', -50.7, 'madurai', 14),
(NEWID(),'Grakata', 'Crita-puracan', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 129.8, 'Infested Damage', 35.8, 'Multishot', 70.9, NULL, NULL, 'madurai', 14),
(NEWID(),'Grakata', 'Decicon', 'CambiarEstoPorIdDeAdmin', 'Status Duration', 110.9, 'Grineer Damage', 44.9, NULL, NULL, NULL, NULL, 'madurai', 14),
(NEWID(),'Grakata', 'Arma-insiada', 'CambiarEstoPorIdDeAdmin', 'Magazine Capacity', 54.8, 'Infested Damage', 42.1, 'Puncture Damage', 112.2, 'Weapon Recoil', 71.7, 'vazarin', 16),
(NEWID(),'Grakata', 'Visitak', 'CambiarEstoPorIdDeAdmin', 'Damage', 189.2, 'Reload Speed', 56.5, NULL, NULL, NULL, NULL, 'vazarin', 16),
(NEWID(),'Grakata', 'Ignides', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 91.6, 'Status Duration', 99.5, NULL, NULL, NULL, NULL, 'naramon', 16),
(NEWID(),'Grakata', 'Manti-puracan', 'CambiarEstoPorIdDeAdmin', 'Multishot', 67.8, 'Corpus Damage', 36.6, 'Infested Damage', 34.9, NULL, NULL, 'naramon', 16),
(NEWID(),'Grakata', 'Magnatak', 'CambiarEstoPorIdDeAdmin', 'Impact Damage', 179.2, 'Reload Speed', 63.1, NULL, NULL, 'Status Duration', -52.3, 'madurai', 16),
(NEWID(),'Grinlok', 'Igniton', 'CambiarEstoPorIdDeAdmin', 'Impact Damage', 135.5, 'Heat Damage', 108.4, NULL, NULL, NULL, NULL, 'vazarin', 8),
(NEWID(),'Grinlok', 'Magna-Zetinok', 'CambiarEstoPorIdDeAdmin', 'Weapon Recoil', -82.1, 'Punch Through', 210.0, 'Impact Damage', 121.3, NULL, NULL, 'madurai', 9),
(NEWID(),'Grinlok', 'Ampicron', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 229.7, 'Ammo maximum', 83.0, NULL, NULL, 'Magazine Capacity', -33.0, 'madurai', 15),
(NEWID(),'Grinlok', 'Sati-critaton', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 182.1, 'Impact Damage', 127.6, 'Multishot', 114.3, 'Zoom', -57.1, 'madurai', 15),
(NEWID(),'Grinlok', 'Lexi-scitron', 'CambiarEstoPorIdDeAdmin', 'Punch Through', 310.0, 'Corpus Damage', 50.2, 'Slash Damage', 146.6, 'Impact Damage', -112.6, 'madurai', 16),
(NEWID(),'Harpak', 'Visinak', 'CambiarEstoPorIdDeAdmin', 'Damage', 302.6, 'Flight Speed', 149.6, NULL, NULL, 'Impact Damage', -76.4, 'vazarin', 14),
(NEWID(),'Harpak', 'Magna-mantibin', 'CambiarEstoPorIdDeAdmin', 'Ammo maximum', 65.1, 'Corpus Damage', 59.1, 'Impact Damage', 163.7, 'Reload Speed', -50.7, 'madurai', 15),
(NEWID(),'Harpak', 'Satibin', 'CambiarEstoPorIdDeAdmin', 'Ammo maximum', 86.5, 'Multishot', 169.0, NULL, NULL, 'Reload Speed', -35.4, 'vazarin', 16),
(NEWID(),'Harpak', 'Arma-visicron', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 182.3, 'Magazine Capacity', 62.8, 'Damage', 203.2, 'Flight Speed', -92.6, 'naramon', 16),
(NEWID(),'Harpak', 'Vexi-fevatin', 'CambiarEstoPorIdDeAdmin', 'Reload Speed', 54.9, 'Magazine Capacity', 47.3, 'Electric Damage', 99.9, NULL, NULL, 'naramon', 15),
(NEWID(),'Hind', 'Geli-scicon', 'CambiarEstoPorIdDeAdmin', 'Cold Damage', 129.9, 'Grineer Damage', 54.6, 'Slash Damage', 147.0, 'Critical Chance', -156.8, 'vazarin', 10),
(NEWID(),'Hind', 'Lexi-Critatox', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 193.3, 'Toxin Damage', 109.1, 'Punch Through', NULL, 'Damage', -185.4, 'madurai', 15),
(NEWID(),'Hind', 'Visi-toxipha', 'CambiarEstoPorIdDeAdmin', 'Damage', 187.1, 'Heat Damage', 88.5, 'Toxin Damage', 98.5, NULL, NULL, 'vazarin', 15),
(NEWID(),'Ignis', 'Zetiada', 'CambiarEstoPorIdDeAdmin', 'Infested Damage', 39.7, 'Weapon Recoil', -85.8, NULL, NULL, 'Status Chance', -32.2, 'madurai', 10),
(NEWID(),'Ignis', 'Armatis', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 125.3, 'Magazine Capacity', 52.2, NULL, NULL, 'Fire Rate', -24.2, 'madurai', 10),
(NEWID(),'Ignis', 'Lexi-visidra', 'CambiarEstoPorIdDeAdmin', 'Fire Rate', 41.6, 'Punch Through', 200.0, 'Damage', 122.5, 'Zoom', -38.5, 'madurai', 10),
(NEWID(),'Ignis', 'Hexa-ignido', 'CambiarEstoPorIdDeAdmin', 'Status Chance', 70.3, 'Cold Damage', 62.2, 'Heat Damage', 64.9, 'Ammo maximum', -27.2, 'vazarin', 11),
(NEWID(),'Ignis', 'Saticron', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 116.7, 'Multishot', 71.4, NULL, NULL, NULL, NULL, 'vazarin', 11),
(NEWID(),'Ignis', 'Acri-decipha', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 52.0, 'Critical Damage', 72.7, 'Status Duration', 60.3, NULL, NULL, 'vazarin', 11),
(NEWID(),'Ignis', 'Hexaata', 'CambiarEstoPorIdDeAdmin', 'Status Chance', 94.5, 'Damage', 147.7, NULL, NULL, 'Infested Damage', -17.6, 'naramon', 11),
(NEWID(),'Ignis', 'Sati-visitox', 'CambiarEstoPorIdDeAdmin', 'Multishot', 67.7, 'Toxin Damage', 63.9, 'Damage', 118.1, 'Fire Rate', -37.5, 'madurai', 11),
(NEWID(),'Ignis', 'Hexa-Lexitak', 'CambiarEstoPorIdDeAdmin', 'Reload Speed', 27.4, 'Punch Through', NULL, 'Status Chance', 55.6, NULL, NULL, 'vazarin', 13),
(NEWID(),'Ignis', 'Acriata', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 99.9, 'Damage', 120.9, NULL, NULL, NULL, NULL, 'vazarin', 14),
(NEWID(),'Ignis', 'Hera-croniada', 'CambiarEstoPorIdDeAdmin', 'Fire Rate', 42.4, 'Infested Damage', 31.2, 'Zoom', 44.7, 'Reload Speed', -27.2, 'madurai', 15),
(NEWID(),'Ignis', 'Hexa-visido', 'CambiarEstoPorIdDeAdmin', 'Cold Damage', 49.0, 'Damage', 97.2, 'Status Chance', 54.7, NULL, NULL, 'madurai', 15),
(NEWID(),'Ignis', 'Sati-cronicron', 'CambiarEstoPorIdDeAdmin', 'Fire Rate', 33.6, 'Multishot', 54.3, 'Critical Chance', 80.0, NULL, NULL, 'madurai', 15),
(NEWID(),'Ignis', 'Feva-hexado', 'CambiarEstoPorIdDeAdmin', 'Reload Speed', 31.1, 'Cold Damage', 50.4, 'Status Chance', 51.4, NULL, NULL, 'madurai', 15),
(NEWID(),'Ignis', 'Heraata', 'CambiarEstoPorIdDeAdmin', 'Zoom', 49.9, 'Damage', 134.1, NULL, NULL, NULL, NULL, 'madurai', 15),
(NEWID(),'Ignis', 'Visi-argican', 'CambiarEstoPorIdDeAdmin', 'Multishot', 48.4, 'Grineer Damage', 28.2, 'Damage', 106.5, NULL, NULL, 'madurai', 15),
(NEWID(),'Ignis', 'Manti-toxitio', 'CambiarEstoPorIdDeAdmin', 'Corpus Damage', 28.4, 'Electric Damage', 53.2, 'Toxin Damage', 55.9, NULL, NULL, 'naramon', 16),
(NEWID(),'Ignis', 'Satitin', 'CambiarEstoPorIdDeAdmin', 'Multishot', 70.2, 'Magazine Capacity', 38.2, NULL, NULL, NULL, NULL, 'vazarin', 16),
(NEWID(),'Ignis', 'Gelitron', 'CambiarEstoPorIdDeAdmin', 'Cold Damage', 73.5, 'Corpus Damage', 33.7, NULL, NULL, NULL, NULL, 'naramon', 8),
(NEWID(),'Karak', 'Hera-Lexicron', 'CambiarEstoPorIdDeAdmin', 'Punch Through', 360.0, 'Critical Chance', 192.6, 'Zoom', 78.3, 'Ammo maximum', -46.8, 'madurai', 10),
(NEWID(),'Karak', 'Sci-critaada', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 151.2, 'Slash Damage', 123.3, 'Infested Damage', 43.2, NULL, NULL, 'madurai', 10),
(NEWID(),'Karak', 'Visisus', 'CambiarEstoPorIdDeAdmin', 'Damage', 260.3, 'Slash Damage', 181.6, NULL, NULL, 'Puncture Damage', -76.8, 'madurai', 13),
(NEWID(),'Karak', 'Insi-magnatio', 'CambiarEstoPorIdDeAdmin', 'Puncture Damage', 150.4, 'Electric Damage', 99.4, 'Impact Damage', 134.7, 'Critical Chance', -153.2, 'vazarin', 14),
(NEWID(),'Karak', 'Saticron', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 191.0, 'Multishot', 119.8, NULL, NULL, NULL, NULL, 'vazarin', 15),
(NEWID(),'Karak', 'Zetitox', 'CambiarEstoPorIdDeAdmin', 'Toxin Damage', 106.4, 'Weapon Recoil', -118.7, NULL, NULL, NULL, NULL, 'madurai', 16),
(NEWID(),'Karak', 'Sati-mantitio', 'CambiarEstoPorIdDeAdmin', 'Corpus Damage', 44.5, 'Multishot', 92.7, 'Electric Damage', 78.1, NULL, NULL, 'naramon', 13),
(NEWID(),'Karak', 'Visitox', 'CambiarEstoPorIdDeAdmin', 'Toxin Damage', 129.9, 'Damage', 277.8, NULL, NULL, 'Impact Damage', -79.5, 'naramon', 18),
(NEWID(),'Lanka', 'Ampi-satiata', 'CambiarEstoPorIdDeAdmin', 'Multishot', 87.1, 'Damage', 154.6, 'Ammo maximum', 53.1, 'Grineer Damage', -39.1, 'vazarin', 8),
(NEWID(),'Lanka', 'Toxi-satido', 'CambiarEstoPorIdDeAdmin', 'Toxin Damage', 90.3, 'Multishot', 87.8, 'Cold Damage', 85.5, 'Grineer Damage', -40.3, 'vazarin', 8),
(NEWID(),'Lanka', 'Vexi-acricon', 'CambiarEstoPorIdDeAdmin', 'Electric Damage', 99.7, 'Grineer Damage', 42.5, 'Critical Damage', 127.9, 'Fire Rate', -48.3, 'vazarin', 9),
(NEWID(),'Lanka', 'Visi-concitin', 'CambiarEstoPorIdDeAdmin', 'Magazine Capacity', 40.8, 'Damage', 141.6, 'Flight Speed', 75.0, NULL, NULL, 'madurai', 10),
(NEWID(),'Lanka', 'Arma-toxitak', 'CambiarEstoPorIdDeAdmin', 'Reload Speed', 48.9, 'Toxin Damage', 94.9, 'Magazine Capacity', 55.6, 'Critical Damage', -102.4, 'madurai', 11),
(NEWID(),'Lanka', 'lexi-puraata', 'CambiarEstoPorIdDeAdmin', 'Punch Through', 270.0, 'Infested Damage', 48.0, 'Damage', 157.4, 'Critical Damage', -105.9, 'vazarin', 12),
(NEWID(),'Lanka', 'Igni-visidra', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 77.1, 'Fire Rate', 50.0, 'Damage', 138.8, NULL, NULL, 'vazarin', 12),
(NEWID(),'Lanka', 'Visican', 'CambiarEstoPorIdDeAdmin', 'Multishot', 123.6, 'Damage', 228.1, NULL, NULL, 'Status Chance', -49.0, 'madurai', 14),
(NEWID(),'Lanka', 'Sati-conciata', 'CambiarEstoPorIdDeAdmin', 'Multishot', 97.4, 'Flight Speed', 96.9, 'Damage', 168.7, 'Critical Chance', -134.9, 'naramon', 16),
(NEWID(),'Lanka', 'Mgna-heratis', 'CambiarEstoPorIdDeAdmin', 'Zoom', 51.6, 'Critical Damage', 95.7, 'Impact Damage', 105.4, NULL, NULL, 'madurai', 16),
(NEWID(),'Lanka', 'Deciata', 'CambiarEstoPorIdDeAdmin', 'Status Duration', 144.0, 'Damage', 228.1, NULL, NULL, 'Infested Damage', -25.6, 'naramon', 16),
(NEWID(),'Latron', 'Vexipha', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 89.3, 'Electric Damage', 99.6, NULL, NULL, NULL, NULL, 'vazarin', 9),
(NEWID(),'Latron', 'Ampi-cronilis', 'CambiarEstoPorIdDeAdmin', 'Ammo maximum', 53.7, 'Zoom', 57.6, 'Fire Rate', 62.3, 'Magazine Capacity', -37.9, 'madurai', 10),
(NEWID(),'Latron', 'Cronimag', 'CambiarEstoPorIdDeAdmin', 'Weapon Recoil', -111.8, 'Fire Rate', 84.7, NULL, NULL, 'Ammo maximum', -27.7, 'vazarin', 12),
(NEWID(),'Latron', 'Critades', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 210.3, 'Status Duration', 120.4, NULL, NULL, 'Reload Speed', -28.2, 'madurai', 12),
(NEWID(),'Latron', 'Acri-Toxican', 'CambiarEstoPorIdDeAdmin', 'Toxin Damage', 72.8, 'Critical Damage', 98.0, 'Multishot', 67.1, NULL, NULL, 'naramon', 12),
(NEWID(),'Latron', 'Visi-satides', 'CambiarEstoPorIdDeAdmin', 'Damage', 179.0, 'Status Duration', 95.7, 'Multishot', 90.1, 'Grineer Damage', -32.6, 'vazarin', 13),
(NEWID(),'Latron', 'Igni-critades', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 75.1, 'Status Duration', 75.0, 'Critical Chance', 113.1, NULL, NULL, 'vazarin', 13),
(NEWID(),'Latron', 'Fevatox', 'CambiarEstoPorIdDeAdmin', 'Toxin Damage', 96.9, 'Reload Speed', 54.2, NULL, NULL, NULL, NULL, 'vazarin', 13),
(NEWID(),'Latron', 'Hexatak', 'CambiarEstoPorIdDeAdmin', 'Reload Speed', 63.9, 'Status Chance', 117.0, NULL, NULL, 'Fire Rate', -32.4, 'madurai', 14),
(NEWID(),'Latron', 'Argidex', 'CambiarEstoPorIdDeAdmin', 'Grineer Damage', 57.6, 'Status Chance', 108.0, NULL, NULL, 'Magazine Capacity', -27.9, 'madurai', 14),
(NEWID(),'Latron', 'Leximag', 'CambiarEstoPorIdDeAdmin', 'Weapon Recoil', -111.6, 'Punch Through', 360.0, NULL, NULL, 'Multishot', -50.4, 'madurai', 14),
(NEWID(),'Latron', 'Deci-hexacon', 'CambiarEstoPorIdDeAdmin', 'Grineer Damage', 33.3, 'Status Chance', 75.6, 'Status Duration', 85.5, NULL, NULL, 'madurai', 14),
(NEWID(),'Latron', 'Acricak', 'CambiarEstoPorIdDeAdmin', 'Puncture Damage', 117.0, 'Critical Damage', 125.1, NULL, NULL, NULL, NULL, 'madurai', 14),
(NEWID(),'Latron', 'Manta-fevabin', 'CambiarEstoPorIdDeAdmin', 'Reload Speed', 42.3, 'Corpus Damage', 39.6, 'Ammo maximum', 42.3, NULL, NULL, 'madurai', 14),
(NEWID(),'Latron', 'Cronibin', 'CambiarEstoPorIdDeAdmin', 'Ammo maximum', 63.4, 'Fire Rate', 77.3, NULL, NULL, 'Multishot', -48.7, 'madurai', 16),
(NEWID(),'Latron', 'Acri-cronicon', 'CambiarEstoPorIdDeAdmin', 'Grineer Damage', 33.2, 'Critical Damage', 90.4, 'Fire Rate', 45.0, NULL, NULL, 'vazarin', 16),
(NEWID(),'Latron', 'Lexi-visimag', 'CambiarEstoPorIdDeAdmin', 'Weapon Recoil', -69.0, 'Damage', 141.2, 'Punch Through', 2.2, NULL, NULL, 'naramon', 10),
(NEWID(),'Latron', 'Visido', 'CambiarEstoPorIdDeAdmin', 'Damage', 187.8, 'Cold Damage', 91.6, NULL, NULL, NULL, NULL, 'naramon', 10),
(NEWID(),'Latron', 'Feva-visimag', 'CambiarEstoPorIdDeAdmin', 'Weapon Recoil', -65.2, 'Reload Speed', 40.8, 'Damage', 130.1, NULL, NULL, 'vazarin', 12),
(NEWID(),'Latron', 'Critatio', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 212.0, 'Electric Damage', 108.2, NULL, NULL, 'Weapon Recoil', 47.6, 'naramon', 10),
(NEWID(),'Latron', 'Visi-puracron', 'CambiarEstoPorIdDeAdmin', 'Damage', 137.6, 'Critical Chance', 108.4, 'Infested Damage', 32.8, NULL, NULL, 'vazarin', 10),
(NEWID(),'Latron', 'Heratio', 'CambiarEstoPorIdDeAdmin', 'Zoom', 63.6, 'Electric Damage', 92.1, NULL, NULL, NULL, NULL, 'vazarin', 15),
(NEWID(),'Miter', 'Argi-concitox', 'CambiarEstoPorIdDeAdmin', 'Grineer Damage', 50.2, 'Flight Speed', 89.0, 'Toxin Damage', 88.0, NULL, NULL, 'naramon', 8),
(NEWID(),'Miter', 'Geli-Toxitron', 'CambiarEstoPorIdDeAdmin', 'Cold Damage', 99.5, 'Toxin Damage', 92.9, 'Corpus Damage', 45.9, NULL, NULL, 'madurai', 10),
(NEWID(),'Miter', 'Acrican', 'CambiarEstoPorIdDeAdmin', 'Multishot', 129.0, 'Critical Damage', 175.9, NULL, NULL, NULL, NULL, 'vazarin', 10),
(NEWID(),'Miter', 'Toxi-deciada', 'CambiarEstoPorIdDeAdmin', 'Infested Damage', 47.1, 'Status Duration', 108.0, 'Toxin Damage', 100.6, NULL, NULL, 'vazarin', 11),
(NEWID(),'Miter', 'Deci-visitin', 'CambiarEstoPorIdDeAdmin', 'Status Duration', 115.8, 'Damage', 183.6, 'Magazine Capacity', 51.4, NULL, NULL, 'naramon', 12),
(NEWID(),'Miter', 'Sati-hexatron', 'CambiarEstoPorIdDeAdmin', 'Multishot', 103.8, 'Status Chance', 92.9, 'Corpus Damage', 43.8, NULL, NULL, 'naramon', 13),
(NEWID(),'Miter', 'Vexidra', 'CambiarEstoPorIdDeAdmin', 'Electric Damage', 172.2, 'Fire Rate', 100.3, NULL, NULL, 'Zoom', -45.4, 'madurai', 14),
(NEWID(),'Miter', 'Cronipha', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 156.9, 'Fire Rate', 111.4, NULL, NULL, 'Zoom', -43.5, 'madurai', 14),
(NEWID(),'Miter', 'Hexacon', 'CambiarEstoPorIdDeAdmin', 'Grineer Damage', 59.5, 'Status Chance', 133.6, NULL, NULL, NULL, NULL, 'madurai', 14),
(NEWID(),'Miter', 'Fevaata', 'CambiarEstoPorIdDeAdmin', 'Reload Speed', 76.2, 'Damage', 213.2, NULL, NULL, NULL, NULL, 'madurai', 14),
(NEWID(),'Miter', 'Magnatis', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 152.1, 'Impact Damage', 164.9, NULL, NULL, NULL, NULL, 'madurai', 16),
(NEWID(),'Miter', 'Deci-lexiata', 'CambiarEstoPorIdDeAdmin', 'Punch Through', 250.0, 'Damage', 163.9, 'Status Duration', 109.3, NULL, NULL, 'naramon', 10),
(NEWID(),'Miter', 'Manti-critatis', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 144.9, 'Corpus Damage', 59.8, 'Critical Chance', 183.9, 'Impact Damage', -122.4, 'naramon', 8),
(NEWID(),'Mutalist Cernos', 'Hexacan', 'CambiarEstoPorIdDeAdmin', 'Status Chance', 144.0, 'Multishot', 132.8, NULL, NULL, 'Magazine Capacity', -30.2, 'vazarin', 10),
(NEWID(),'Mutalist Cernos', 'Hexaata', 'CambiarEstoPorIdDeAdmin', 'Status Chance', 114.1, 'Damage', 178.4, NULL, NULL, NULL, NULL, 'madurai', 8),
(NEWID(),'Mutalist Cernos', 'Crita-mantiton', 'CambiarEstoPorIdDeAdmin', 'Impact Damage', 110.4, 'Critical Chance', 145.6, 'Corpus Damage', 43.4, NULL, NULL, 'madurai', 10),
(NEWID(),'Mutalist Cernos', 'Cronitox', 'CambiarEstoPorIdDeAdmin', 'Toxin Damage', 103.0, 'Fire Rate', 69.1, NULL, NULL, NULL, NULL, 'madurai', 8),
(NEWID(),'Mutalist Cernos', 'Vexicron', 'CambiarEstoPorIdDeAdmin', 'Electric Damage', 115.6, 'Critical Chance', 167.6, NULL, NULL, NULL, NULL, 'madurai', 10),
(NEWID(),'Mutalist Cernos', 'Igni-Decinak', 'CambiarEstoPorIdDeAdmin', 'Status Duration', 86.1, 'Heat Damage', 79.2, 'Flight Speed', 73.8, NULL, NULL, 'madurai', 16),
(NEWID(),'Mutalist Cernos', 'Geli-herades', 'CambiarEstoPorIdDeAdmin', 'Cold Damage', 89.9, 'Zoom', 51.1, 'Status Duration', 83.7, NULL, NULL, 'naramon', 15),
(NEWID(),'Ogris', 'Zeti-magnanok', 'CambiarEstoPorIdDeAdmin', 'Weapon Recoil', -96.9, 'Punch Through', 270.0, 'Impact Damage', 129.1, 'Critical Chance', -126.9, 'vazarin', 15),
(NEWID(),'Ogris', 'Igni-Satiton', 'CambiarEstoPorIdDeAdmin', 'Impact Damage', 126.7, 'Heat Damage', -107.8, 'Multishot', 100.7, 'Damage', -149.1, 'vazarin', 18),
(NEWID(),'Ogris', 'Toxipha', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 115.9, 'Toxin Damage', 119.2, NULL, NULL, NULL, NULL, 'vazarin', 18),
(NEWID(),'Ogris', 'Purades', 'CambiarEstoPorIdDeAdmin', 'Infested Damage', 76.2, 'Status Duration', 153.4, 'Status Chance', -61.0, NULL, NULL, 'vazarin', 18),
(NEWID(),'Ogris', 'Visitox', 'CambiarEstoPorIdDeAdmin', 'Damage', 203.4, 'Toxin Damage', 110.6, NULL, NULL, NULL, NULL, 'vazarin', 11),
(NEWID(),'Opticor', 'Insi-visican', 'CambiarEstoPorIdDeAdmin', 'Multishot', 95.3, 'Puncture Damage', 146.0, 'Damage', 185.3, 'Ammo maximum', -44.3, 'naramon', 11),
(NEWID(),'Opticor', 'Ignido', 'CambiarEstoPorIdDeAdmin', 'Cold Damage', 144.3, 'Heat Damage', 147.0, NULL, NULL, 'Corpus Damage', -27.4, 'madurai', 11),
(NEWID(),'Opticor', 'Insi-visitak', 'CambiarEstoPorIdDeAdmin', 'Puncture Damage', 141.2, 'Damage', 182.0, 'Reload Speed', 52.5, 'Magazine Capacity', -43.6, 'madurai', 14),
(NEWID(),'Opticor', 'Critacan', 'CambiarEstoPorIdDeAdmin', 'Multishot', 129.3, 'Critical Chance', 229.2, NULL, NULL, 'Grineer Damage', -25.6, 'vazarin', 16),
(NEWID(),'Opticor', 'Ingi-acricron', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 143.7, 'Heat Damage', 112.2, 'Critical Chance', 178.5, 'Corpus Damage', -38.1, 'naramon', 9),
(NEWID(),'Panthera', 'Zetican', 'CambiarEstoPorIdDeAdmin', 'Multishot', 142.4, 'Weapon Recoil', -150.8, NULL, NULL, 'Critical Damage', -75.0, 'vazarin', 11),
(NEWID(),'Paris', 'Manti-purades', 'CambiarEstoPorIdDeAdmin', 'Corpus Damage', 33.3, 'Status Duration', 71.8, 'Infested Damage', 32.6, NULL, NULL, 'naramon', 11),
(NEWID(),'Paris', 'Cronitis', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 145.0, 'Fire Rate', 73.8, NULL, NULL, 'Reload Speed', -24.0, 'naramon', 15),
(NEWID(),'Paris', 'Scimag', 'CambiarEstoPorIdDeAdmin', 'Slash Damage', 111.5, 'Weapon Recoil', -82.7, NULL, NULL, NULL, NULL, 'naramon', 13),
(NEWID(),'Penta', 'Argi-ignitak', 'CambiarEstoPorIdDeAdmin', 'Reload Speed', 55.5, 'Heat Damage', 100.2, 'Grineer Damage', 52.9, 'Ammo maximum', -44.1, 'vazarin', 8),
(NEWID(),'Penta', 'Vexi-ampinak', 'CambiarEstoPorIdDeAdmin', 'Electric Damage', 105.3, 'Ammo maximum', 55.8, 'Flight Speed', 100.8, 'Reload Speed', -46.8, 'naramon', 9),
(NEWID(),'Penta', 'Magna-vexitin', 'CambiarEstoPorIdDeAdmin', 'Impact Damage', 113.4, 'Electric Damage', 84.9, 'Magazine Capacity', 46.0, NULL, NULL, 'naramon', 9),
(NEWID(),'Penta', 'Acri-satidex', 'CambiarEstoPorIdDeAdmin', 'Multishot', 100.2, 'Critical Damage', 138.9, 'Status Chance', 95.4, 'Status Duration', -87.1, 'vazarin', 10),
(NEWID(),'Penta', 'Armaata', 'CambiarEstoPorIdDeAdmin', 'Damage', 180.8, 'Magazine Capacity', 56.6, NULL, NULL, NULL, NULL, 'vazarin', 15),
(NEWID(),'Penta', 'Satinak', 'CambiarEstoPorIdDeAdmin', 'Flight Speed', 122.4, 'Multishot', 129.9, NULL, NULL, 'Impact Damage', -71.6, 'naramon', 12),
(NEWID(),'Quanta', 'Igni-gelitis', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 78.8, 'Cold Damage', 73.0, 'Critical Damage', 93.8, 'Flight Speed', -56.7, 'madurai', 13),
(NEWID(),'Quanta', 'Pura-critades', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 127.2, 'Status Duration', 77.7, 'Infested Damage', 38.9, 'Reload Speed', -33.9, 'madurai', 13),
(NEWID(),'Quanta', 'Visi-gelidra', 'CambiarEstoPorIdDeAdmin', 'Fire Rate', 36.4, 'Damage', 119.7, 'Cold Damage', 61.1, NULL, NULL, 'naramon', 13),
(NEWID(),'Quanta', 'Satido', 'CambiarEstoPorIdDeAdmin', 'Multishot', 83.6, 'Cold Damage', 72.5, NULL, NULL, NULL, NULL, 'naramon', 13),
(NEWID(),'Quanta', 'Decimag', 'CambiarEstoPorIdDeAdmin', 'Status Duration', 85.2, 'Weapon Recoil', -73.8, NULL, NULL, NULL, NULL, 'madurai', 13),
(NEWID(),'Quanta', 'Arma-decinak', 'CambiarEstoPorIdDeAdmin', 'Flight Speed', 55.0, 'Status Duration', 67.6, 'Magazine Capacity', 35.2, NULL, NULL, 'madurai', 14),
(NEWID(),'Quanta', 'Satidex', 'CambiarEstoPorIdDeAdmin', 'Multishot', 78.2, 'Status Chance', 74.8, NULL, NULL, NULL, NULL, 'naramon', 15),
(NEWID(),'Quanta', 'Crita-acrican', 'CambiarEstoPorIdDeAdmin', 'Multishot', 62.8, 'Critical Damage', 84.5, 'Critical Chance', 106.9, NULL, NULL, 'vazarin', 18),
(NEWID(),'Rubico', 'Arma-gelipha', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 96.4, 'Cold Damage', 99.6, 'Magazine Capacity', 56.6, 'Corpus Damage', -37.8, 'vazarin', 8),
(NEWID(),'Rubico', 'Cronitox', 'CambiarEstoPorIdDeAdmin', 'Fire Rate', 71.7, 'Toxin Damage', 105.1, NULL, NULL, NULL, NULL, 'vazarin', 12),
(NEWID(),'Rubico', 'Acri-mantitin', 'CambiarEstoPorIdDeAdmin', 'Magazine Capacity', 49.0, 'Critical Damage', 133.2, 'Corpus Damage', 47.3, 'Ammo maximum', -44.4, 'madurai', 13),
(NEWID(),'Rubico', 'Deci-Toxinron', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 117.0, 'Status Duration', 90.0, 'Toxin Damage', 74.7, NULL, NULL, 'vazarin', 15),
(NEWID(),'Simulor', 'Vexi-insitak', 'CambiarEstoPorIdDeAdmin', 'Electric Damage', 56.6, 'Puncture Damage', 71.4, 'Reload Speed', 29.1, 'Ammo maximum', -25.5, 'naramon', 8),
(NEWID(),'Simulor', 'Lexi-amitio', 'CambiarEstoPorIdDeAdmin', 'Ammo maximum', 31.2, 'Electric Damage', 55.0, 'Punch Through', 160.0, 'Corpus Damage', -21.0, 'naramon', 8),
(NEWID(),'Simulor', 'Insido', 'CambiarEstoPorIdDeAdmin', 'Puncture Damage', 95.1, 'Cold Damage', 65.7, NULL, NULL, 'Critical Chance', -49.5, 'naramon', 8),
(NEWID(),'Simulor', 'Argitio', 'CambiarEstoPorIdDeAdmin', 'Electric Damage', 60.7, 'Grineer Damage', 30.5, NULL, NULL, NULL, NULL, 'naramon', 8),
(NEWID(),'Simulor', 'Visides', 'CambiarEstoPorIdDeAdmin', 'Status Duration', 75.1, 'Damage', 134.9, NULL, NULL, 'Status Chance', -29.9, 'vazarin', 10),
(NEWID(),'Simulor', 'Croni-lexican', 'CambiarEstoPorIdDeAdmin', 'Multishot', 40.0, 'Punch Through', 110.0, 'Fire Rate', 29.8, NULL, NULL, 'vazarin', 10),
(NEWID(),'Simulor', 'Igni-vexido', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 59.7, 'Cold Damage', 55.8, 'Electric Damage', 59.4, 'Infested Damage', -22.1, 'madurai', 11),
(NEWID(),'Simulor', 'Acri-cronimag', 'CambiarEstoPorIdDeAdmin', 'Fire Rate', 30.6, 'Weapon Recoil', -42.3, 'Critical Damage', 61.8, NULL, NULL, 'vazarin', 12),
(NEWID(),'Simulor', 'Toxi-Satinok', 'CambiarEstoPorIdDeAdmin', 'Multishot', 47.4, 'Toxin Damage', 48.2, 'Punch Through', 120.0, NULL, NULL, 'vazarin', 12),
(NEWID(),'Simulor', 'Visi-critaada', 'CambiarEstoPorIdDeAdmin', 'Damage', 81.8, 'Infested Damage', 21.4, 'Critical Chance', 72.7, NULL, NULL, 'madurai', 12),
(NEWID(),'Simulor', 'Deci-acricron', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 74.3, 'Status Duration', 53.1, 'Critical Damage', 61.9, NULL, NULL, 'madurai', 12),
(NEWID(),'Simulor', 'Sci-armacan', 'CambiarEstoPorIdDeAdmin', 'Magazine Capacity', 30.9, 'Multishot', 53.3, 'Slash Damage', 79.2, 'Grineer Damage', -22.3, 'madurai', 12),
(NEWID(),'Simulor', 'Sciata', 'CambiarEstoPorIdDeAdmin', 'Slash Damage', 79.5, 'Damage', 103.8, NULL, NULL, NULL, NULL, 'madurai', 12),
(NEWID(),'Simulor', 'Armatis', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 91.3, 'Magazine Capacity', 38.7, NULL, NULL, 'Fire Rate', -18.8, 'vazarin', 13),
(NEWID(),'Simulor', 'Acritio', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 102.7, 'Electric Damage', 73.2, NULL, NULL, 'Zoom', -19.4, 'naramon', 13),
(NEWID(),'Simulor', 'Cronicron', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 92.2, 'Fire Rate', 38.9, NULL, NULL, NULL, NULL, 'vazarin', 13),
(NEWID(),'Simulor', 'Armatak', 'CambiarEstoPorIdDeAdmin', 'Reload Speed', 30.7, 'Magazine Capacity', 34.9, NULL, NULL, NULL, NULL, 'naramon', 13),
(NEWID(),'Simulor', 'Magna-satitio', 'CambiarEstoPorIdDeAdmin', 'Impact Damage', 76.7, 'Multishot', 51.7, 'Electric Damage', 51.3, 'Fire Rate', -28.8, 'madurai', 14),
(NEWID(),'Simulor', 'Feva-igniton', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 43.4, 'Reload Speed', 26.8, 'Impact Damage', 56.8, NULL, NULL, 'madurai', 15),
(NEWID(),'Simulor', 'Magnaata', 'CambiarEstoPorIdDeAdmin', 'Damage', 128.7, 'Impact Damage', 94.5, NULL, NULL, 'Corpus Damage', -14.4, 'naramon', 16),
(NEWID(),'Simulor', 'Visitin', 'CambiarEstoPorIdDeAdmin', 'Magazine Capacity', 43.4, 'Damage', 145.4, NULL, NULL, 'Slash Damage', -35.6, 'naramon', 16),
(NEWID(),'Simulor', 'Arma-geliton', 'CambiarEstoPorIdDeAdmin', 'Magazine Capacity', 22.9, 'Cold Damage', 40.2, 'Impact Damage', 53.4, NULL, NULL, 'naramon', 16),
(NEWID(),'Simulor', 'Armatio', 'CambiarEstoPorIdDeAdmin', 'Magazine Capacity', 42.8, 'Electric Damage', 70.6, 'Puncture Damage', 42.1, NULL, NULL, 'naramon', 16),
(NEWID(),'Simulor', 'Lexi-Satidex', 'CambiarEstoPorIdDeAdmin', 'Status Chance', 45.1, 'Multishot', 45.2, 'Punch Through', 130.0, NULL, NULL, 'naramon', 16),
(NEWID(),'Simulor', 'Magnamag', 'CambiarEstoPorIdDeAdmin', 'Weapon Recoil', -61.6, 'Impact Damage', 82.7, NULL, NULL, NULL, NULL, 'naramon', 16),
(NEWID(),'Simulor', 'Lexiata', 'CambiarEstoPorIdDeAdmin', 'Punch Through', 1.7, 'Damage', 96.3, NULL, NULL, NULL, NULL, 'naramon', 10),
(NEWID(),'Soma', 'Crita-cronican', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 72.0, 'Multishot', 42.3, 'Fire Rate', 27.9, NULL, NULL, 'vazarin', 10),
(NEWID(),'Soma', 'Satipha', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 52.3, 'Multishot', 52.8, NULL, NULL, NULL, NULL, 'madurai', 10),
(NEWID(),'Soma', 'Sci-gelilis', 'CambiarEstoPorIdDeAdmin', 'Zoom', 27.0, 'Cold Damage', 43.2, 'Slash Damage', 58.4, NULL, NULL, 'naramon', 11),
(NEWID(),'Soma', 'Crita-acritron', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 70.7, 'Critical Chance', 97.0, 'Corpus Damage', 25.2, 'Multishot', -40.0, 'naramon', 12),
(NEWID(),'Soma', 'Vexi-Decidra', 'CambiarEstoPorIdDeAdmin', 'Electric Damage', 59.7, 'Status Duration', 65.0, 'Fire Rate', 36.5, 'Puncture Damage', -54.5, 'madurai', 15),
(NEWID(),'Soma', 'Crita-Gelinok', 'CambiarEstoPorIdDeAdmin', 'Punch Through', 140.0, 'Critical Chance', 89.3, 'Cold Damage', 50.8, 'Slash Damage', -60.9, 'madurai', 15),
(NEWID(),'Soma', 'Zeti-purasus', 'CambiarEstoPorIdDeAdmin', 'Infested Damage', 27.0, 'Weapon Recoil', -59.6, 'Slash Damage', 66.0, 'Ammo maximum', -23.0, 'madurai', 16),
(NEWID(),'Soma', 'Zeti-hexacak', 'CambiarEstoPorIdDeAdmin', 'Puncture Damage', 74.7, 'Weapon Recoil', -60.3, 'Status Chance', 56.7, 'Reload Speed', -25.2, 'madurai', 16),
(NEWID(),'Soma', 'Ampitron', 'CambiarEstoPorIdDeAdmin', 'Ammo maximum', 33.1, 'Corpus Damage', 28.3, NULL, NULL, NULL, NULL, 'vazarin', 13),
(NEWID(),'Soma', 'Croni-gelican', 'CambiarEstoPorIdDeAdmin', 'Cold Damage', 46.1, 'Multishot', 41.4, 'Fire Rate', 31.3, NULL, NULL, 'vazarin', 13),
(NEWID(),'Soma', 'Hera-acrisus', 'CambiarEstoPorIdDeAdmin', 'Slash Damage', 66.5, 'Zoom', 35.1, 'Critical Damage', 69.1, 'Reload Speed', -22.8, 'vazarin', 13),
(NEWID(),'Soma', 'Sati-critalis', 'CambiarEstoPorIdDeAdmin', 'Zoom', 37.9, 'Critical Chance', 94.7, 'Multishot', 58.2, 'Ammo maximum', -23.8, 'vazarin', 13),
(NEWID(),'Soma', 'Toxi-armacan', 'CambiarEstoPorIdDeAdmin', 'Multishot', 50.2, 'Toxin Damage', 55.6, 'Magazine Capacity', 29.3, 'Puncture Damage', -55.9, 'vazarin', 13),
(NEWID(),'Soma', 'Visidex', 'CambiarEstoPorIdDeAdmin', 'Damage', 139.7, 'Status Chance', 73.2, 'Reload Speed', -15.9, NULL, NULL, 'naramon', 9),
(NEWID(),'Soma', 'Visimag', 'CambiarEstoPorIdDeAdmin', 'Weapon Recoil', -54.3, 'Damage', 112.4, NULL, NULL, NULL, NULL, 'vazarin', 13),
(NEWID(),'Soma', 'Visitox', 'CambiarEstoPorIdDeAdmin', 'Toxin Damage', 75.5, 'Damage', 141.3, NULL, NULL, 'Puncture Damage', -39.4, 'vazarin', 13),
(NEWID(),'Soma', 'Visi-vexipha', 'CambiarEstoPorIdDeAdmin', 'Damage', 86.2, 'Heat Damage', 40.2, 'Electric Damage', 45.2, NULL, NULL, 'madurai', 16),
(NEWID(),'Stinger', 'Toxido', 'CambiarEstoPorIdDeAdmin', 'Toxin Damage', 120.5, 'Cold Damage', 114.7, NULL, NULL, NULL, NULL, 'madurai', 14),
(NEWID(),'Stinger', 'Hexa-Lexiton', 'CambiarEstoPorIdDeAdmin', 'Status Chance', 96.9, 'Impact Damage', 120.9, 'Punch Through', 2.6, NULL, NULL, 'vazarin', 12),
(NEWID(),'Stradavar', 'Sati-argitis', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 99.0, 'Multishot', 83.1, 'Grineer Damage', 41.3, NULL, NULL, 'vazarin', 8),
(NEWID(),'Stradavar', 'Sati-armatak', 'CambiarEstoPorIdDeAdmin', 'Multishot', 78.7, 'Magazine Capacity', 43.7, 'Reload Speed', 40.6, NULL, NULL, 'vazarin', 8),
(NEWID(),'Stradavar', 'Vexi-fevapha', 'CambiarEstoPorIdDeAdmin', 'Reload Speed', 53.7, 'Heat Damage', 95.4, 'Electric Damage', 97.0, 'Ammo maximum', -45.9, 'vazarin', 8),
(NEWID(),'Stradavar', 'Insidex', 'CambiarEstoPorIdDeAdmin', 'Puncture Damage', 191.9, 'Status Chance', 119.2, NULL, NULL, 'Ammo maximum', -26.4, 'vazarin', 9),
(NEWID(),'Stradavar', 'Hexasus', 'CambiarEstoPorIdDeAdmin', 'Slash Damage', 136.1, 'Status Chance', 110.5, NULL, NULL, NULL, NULL, 'madurai', 10),
(NEWID(),'Stradavar', 'Satiata', 'CambiarEstoPorIdDeAdmin', 'Multishot', 131.5, 'Damage', 222.0, NULL, NULL, 'Weapon Recoil', 55.2, 'naramon', 11),
(NEWID(),'Stradavar', 'Critatron', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 189.5, 'Corpus Damage', 49.6, NULL, NULL, NULL, NULL, 'vazarin', 14),
(NEWID(),'Stradavar', 'Acri-critacon', 'CambiarEstoPorIdDeAdmin', 'Grineer Damage', 37.2, 'Critical Chance', 130.2, 'Critical Damage', 107.1, NULL, NULL, 'naramon', 14),
(NEWID(),'Stradavar', 'Argitin', 'CambiarEstoPorIdDeAdmin', 'Grineer Damage', 55.8, 'Magazine Capacity', 54.9, NULL, NULL, NULL, NULL, 'naramon', 14),
(NEWID(),'Supra', 'Scitio', 'CambiarEstoPorIdDeAdmin', 'Slash Damage', 169.7, 'Electric Damage', 123.8, NULL, NULL, 'Impact Damage', -65.5, 'madurai', 8),
(NEWID(),'Supra', 'Acri-critado', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 129.4, 'Cold Damage', 70.1, 'Critical Damage', 105.9, NULL, NULL, 'vazarin', 15),
(NEWID(),'Supra', 'Acri-concido', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 109.8, 'Cold Damage', 74.1, 'Flight Speed', 80.3, NULL, NULL, 'vazarin', 15),
(NEWID(),'Supra', 'Vexido', 'CambiarEstoPorIdDeAdmin', 'Electric Damage', 102.5, 'Cold Damage', 96.8, NULL, NULL, NULL, NULL, 'naramon', 15),
(NEWID(),'Supra', 'Cronisus', 'CambiarEstoPorIdDeAdmin', 'Slash Damage', 135.9, 'Fire Rate', 68.3, NULL, NULL, NULL, NULL, 'vazarin', 15),
(NEWID(),'Supra', 'Fevadra', 'CambiarEstoPorIdDeAdmin', 'Reload Speed', 75.4, 'Fire Rate', 88.0, NULL, NULL, 'Infested Damage', -26.2, 'vazarin', 15),
(NEWID(),'Supra', 'Igni-hexacan', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 77.3, 'Multishot', 70.6, 'Status Chance', 74.6, NULL, NULL, 'vazarin', 15),
(NEWID(),'Supra', 'Argides', 'CambiarEstoPorIdDeAdmin', 'Status Duration', 127.1, 'Grineer Damage', 60.4, NULL, NULL, 'Critical Chance', -84.1, 'vazarin', 8),
(NEWID(),'Sybaris', 'Visidex', 'CambiarEstoPorIdDeAdmin', 'Damage', 140.5, 'Status Chance', 73.8, NULL, NULL, NULL, NULL, 'madurai', 10),
(NEWID(),'Sybaris', 'Vexi-visicron', 'CambiarEstoPorIdDeAdmin', 'Electric Damage', 77.7, 'Critical Chance', 113.9, 'Damage', 134.5, 'Status Duration', -67.9, 'vazarin', 11),
(NEWID(),'Sybaris', 'Critaata', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 141.2, 'Damage', 154.3, NULL, NULL, NULL, NULL, 'madurai', 11),
(NEWID(),'Sybaris', 'Zetitin', 'CambiarEstoPorIdDeAdmin', 'Magazine Capacity', 45.1, 'Weapon Recoil', -82.5, NULL, NULL, NULL, NULL, 'vazarin', 12),
(NEWID(),'Sybaris', 'Mantitak', 'CambiarEstoPorIdDeAdmin', 'Corpus Damage', 36.2, 'Reload Speed', 40.0, NULL, NULL, NULL, NULL, 'naramon', 16),
(NEWID(),'Sybaris', 'Arma-cronicon', 'CambiarEstoPorIdDeAdmin', 'Grineer Damage', 35.4, 'Magazine Capacity', 45.8, 'Fire Rate', 49.0, 'Ammo maximum', -36.6, 'madurai', 16),
(NEWID(),'Sybaris', 'Critatak', 'CambiarEstoPorIdDeAdmin', 'Reload Speed', 40.8, 'Critical Chance', 134.9, NULL, NULL, NULL, NULL, 'madurai', 16),
(NEWID(),'Sybaris', 'Satisus', 'CambiarEstoPorIdDeAdmin', 'Slash Damage', 97.9, 'Multishot', 82.6, NULL, NULL, NULL, NULL, 'madurai', 16),
(NEWID(),'Sybaris', 'Crita-argiata', 'CambiarEstoPorIdDeAdmin', 'Grineer Damage', 38.7, 'Critical Chance', 131.0, 'Damage', 130.9, 'Fire Rate', -38.2, 'madurai', 15),
(NEWID(),'Sybaris', 'Acri-visitox', 'CambiarEstoPorIdDeAdmin', 'Damage', 110.6, 'Critical Damage', 82.9, 'Toxin Damage', 58.9, NULL, NULL, 'vazarin', 10),
(NEWID(),'Sybaris', 'Crita-mantiton', 'CambiarEstoPorIdDeAdmin', 'Corpus Damage', 39.0, 'Critical Chance', 136.1, 'Impact Damage', 93.1, 'Status Chance', -66.4, 'naramon', 16),
(NEWID(),'Sybaris', 'Acripha', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 94.1, 'Critical Damage', 131.3, NULL, NULL, 'Zoom', -28.6, 'madurai', 16),
(NEWID(),'Sybaris', 'Visidra', 'CambiarEstoPorIdDeAdmin', 'Damage', 152.0, 'Fire Rate', 54.2, NULL, NULL, NULL, NULL, 'madurai', 16),
(NEWID(),'Synapse', 'Igninok', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 157.3, 'Punch Through', 410.0, NULL, NULL, 'Reload Speed', -33.2, 'vazarin', 8),
(NEWID(),'Synapse', 'Heratis', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 142.1, 'Zoom', 81.1, NULL, NULL, NULL, NULL, 'naramon', 8),
(NEWID(),'Synapse', 'Igni-lexitio', 'CambiarEstoPorIdDeAdmin', 'Punch Through', 250.0, 'Heat Damage', 92.0, 'Electric Damage', 84.5, NULL, NULL, 'madurai', 8),
(NEWID(),'Synapse', 'Deci-visitis', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 109.5, 'Damage', 169.2, 'Status Duration', 104.6, NULL, NULL, 'madurai', 9),
(NEWID(),'Synapse', 'Critapha', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 118.2, 'Critical Chance', 209.6, NULL, NULL, NULL, NULL, 'naramon', 9),
(NEWID(),'Synapse', 'Visiada', 'CambiarEstoPorIdDeAdmin', 'Infested Damage', 57.2, 'Damage', 235.9, NULL, NULL, NULL, NULL, 'vazarin', 9),
(NEWID(),'Synapse', 'Saticron', 'CambiarEstoPorIdDeAdmin', 'Multishot', 159.9, 'Critical Chance', 230.3, NULL, NULL, 'Damage', -100.3, 'madurai', 12),
(NEWID(),'Synapse', 'Crita-armadra', 'CambiarEstoPorIdDeAdmin', 'Fire Rate', 54.0, 'Magazine Capacity', 52.4, 'Critical Chance', 159.7, NULL, NULL, 'madurai', 12),
(NEWID(),'Synapse', 'Pura-visitox', 'CambiarEstoPorIdDeAdmin', 'Toxin Damage', 87.3, 'Damage', 167.6, 'Infested Damage', 47.9, NULL, NULL, 'vazarin', 12),
(NEWID(),'Synapse', 'Visi-critatis', 'CambiarEstoPorIdDeAdmin', 'Damage', 163.3, 'Critical Damage', 107.8, 'Critical Chance', 136.1, NULL, NULL, 'vazarin', 13),
(NEWID(),'Synapse', 'Igniada', 'CambiarEstoPorIdDeAdmin', 'Infested Damage', 57.0, 'Heat Damage', 117.3, NULL, NULL, NULL, NULL, 'naramon', 14),
(NEWID(),'Synapse', 'Zeti-acricron', 'CambiarEstoPorIdDeAdmin', 'Weapon Recoil', -121.9, 'Critical Chance', 175.6, 'Critical Damage', 144.9, 'Magazine Capacity', -49.5, 'vazarin', 10),
(NEWID(),'Synapse', 'Critatin', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 260.0, 'Magazine Capacity', 85.4, NULL, NULL, 'Status Chance', -53.5, 'vazarin', 12),
(NEWID(),'Tetra', 'Acriton', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 218.4, 'Impact Damage', 191.3, NULL, NULL, 'Reload Speed', -36.2, 'vazarin', 8),
(NEWID(),'Tetra', 'Cronides', 'CambiarEstoPorIdDeAdmin', 'Status Duration', 160.1, 'Fire Rate', 105.7, NULL, NULL, 'Zoom', -43.3, 'naramon', 10),
(NEWID(),'Tetra', 'Leximag', 'CambiarEstoPorIdDeAdmin', 'Weapon Recoil', -142.8, 'Punch Through', 450.0, NULL, NULL, 'Damage', -105.5, 'naramon', 11),
(NEWID(),'Tetra', 'Lexi-visicon', 'CambiarEstoPorIdDeAdmin', 'Grineer Damage', 52.4, 'Damage', 209.3, 'Punch Through', 3.4, 'Status Chance', -93.4, 'vazarin', 11),
(NEWID(),'Tetra', 'Visi-puracan', 'CambiarEstoPorIdDeAdmin', 'Multishot', 93.2, 'Infested Damage', 47.6, 'Damage', 178.4, NULL, NULL, 'vazarin', 16),
(NEWID(),'Tiberon', 'Fevatin', 'CambiarEstoPorIdDeAdmin', 'Magazine Capacity', 82.9, 'Reload Speed', 88.5, NULL, NULL, 'Zoom', -36.8, 'naramon', 9),
(NEWID(),'Tiberon', 'Argi-insidex', 'CambiarEstoPorIdDeAdmin', 'Status Chance', 111.3, 'Grineer Damage', 61.7, 'Puncture Damage', 160.2, 'Zoom', -66.2, 'naramon', 9),
(NEWID(),'Tiberon', 'Feva-mantiata', 'CambiarEstoPorIdDeAdmin', 'Damage', 162.9, 'Corpus Damage', 46.7, 'Reload Speed', 55.6, NULL, NULL, 'naramon', 9),
(NEWID(),'Tiberon', 'Vexi-Toxinan', 'CambiarEstoPorIdDeAdmin', 'Toxin Damage', 110.4, 'Electric Damage', 115.7, 'Multishot', 104.5, 'Fire Rate', -60.5, 'madurai', 10),
(NEWID(),'Tiberon', 'Argidex', 'CambiarEstoPorIdDeAdmin', 'Status Chance', 118.1, 'Grineer Damage', 65.7, NULL, NULL, NULL, NULL, 'vazarin', 10),
(NEWID(),'Tiberon', 'Toxi-decitin', 'CambiarEstoPorIdDeAdmin', 'Status Duration', 123.4, 'Toxin Damage', 116.4, 'Magazine Capacity', 59.4, 'Reload Speed', -49.4, 'madurai', 13),
(NEWID(),'Tiberon', 'Pura-Zeticon', 'CambiarEstoPorIdDeAdmin', 'Weapon Recoil', -90.6, 'Infested Damage', 47.4, 'Grineer Damage', 42.2, NULL, NULL, 'naramon', 13),
(NEWID(),'Tiberon', 'Vexiata', 'CambiarEstoPorIdDeAdmin', 'Electric Damage', 126.9, 'Damage', 213.5, NULL, NULL, NULL, NULL, 'vazarin', 14),
(NEWID(),'Tiberon', 'Zeti-insiata', 'CambiarEstoPorIdDeAdmin', 'Weapon Recoil', -99.6, 'Damage', 165.7, 'Puncture Damage', 126.7, NULL, NULL, 'vazarin', 15),
(NEWID(),'Tiberon', 'Visican', 'CambiarEstoPorIdDeAdmin', 'Multishot', 142.7, 'Damage', 277.2, NULL, NULL, 'Critical Chance', -107.6, 'naramon', 16),
(NEWID(),'Tonkor', 'Zeti-acriata', 'CambiarEstoPorIdDeAdmin', 'Weapon Recoil', -49.6, 'Critical Chance', 65.3, 'Damage', 78.4, NULL, NULL, 'vazarin', 8),
(NEWID(),'Tonkor', 'Critaata', 'CambiarEstoPorIdDeAdmin', 'Damage', 126.5, 'Critical Chance', 128.4, NULL, NULL, 'Zoom', -20.5, 'madurai', 10),
(NEWID(),'Tonkor', 'Hexamag', 'CambiarEstoPorIdDeAdmin', 'Status Chance', 79.5, 'Weapon Recoil', -73.1, NULL, NULL, 'Critical Damage', -43.1, 'naramon', 11),
(NEWID(),'Tonkor', 'Sati-mantinak', 'CambiarEstoPorIdDeAdmin', 'Multishot', 59.4, 'Corpus Damage', 28.2, 'Flight Speed', 53.7, 'Damage', -88.6, 'naramon', 11),
(NEWID(),'Tonkor', 'Visi-acrinak', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 82.0, 'Flight Speed', 60.2, 'Damage', 115.2, 'Grineer Damage', -24.9, 'naramon', 11),
(NEWID(),'Tonkor', 'Manti-puratio', 'CambiarEstoPorIdDeAdmin', 'Electric Damage', 56.3, 'Infested Damage', 28.6, 'Corpus Damage', 30.9, 'Grineer Damage', -24.4, 'naramon', 11),
(NEWID(),'Tonkor', 'Geli-zetiada', 'CambiarEstoPorIdDeAdmin', 'Cold Damage', 61.9, 'Weapon Recoil', -57.2, 'Infested Damage', 27.0, 'Multishot', -43.3, 'naramon', 11),
(NEWID(),'Tonkor', 'Croninak', 'CambiarEstoPorIdDeAdmin', 'Flight Speed', 56.5, 'Fire Rate', 40.2, NULL, NULL, NULL, NULL, 'naramon', 11),
(NEWID(),'Tonkor', 'Herabin', 'CambiarEstoPorIdDeAdmin', 'Zoom', 44.2, 'Ammo maximum', 33.8, NULL, NULL, NULL, NULL, 'naramon', 11),
(NEWID(),'Tonkor', 'Satitis', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 82.4, 'Multishot', 66.1, NULL, NULL, NULL, NULL, 'naramon', 14),
(NEWID(),'Tonkor', 'Ampi-acriata', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 75.2, 'Damage', 102.4, 'Ammo maximum', 32.8, 'Fire Rate', -28.2, 'vazarin', 15),
(NEWID(),'Tonkor', 'Sati-puradex', 'CambiarEstoPorIdDeAdmin', 'Multishot', 47.4, 'Status Chance', 43.1, 'Infested Damage', 22.2, NULL, NULL, 'vazarin', 15),
(NEWID(),'Tonkor', 'Acri-visidex', 'CambiarEstoPorIdDeAdmin', 'Damage', 80.8, 'Status Chance', 41.8, 'Critical Damage', 63.3, NULL, NULL, 'vazarin', 16),
(NEWID(),'Tonkor', 'Feva-acrican', 'CambiarEstoPorIdDeAdmin', 'Multishot', 42.4, 'Reload Speed', 28.2, 'Critical Damage', 66.5, NULL, NULL, 'madurai', 8),
(NEWID(),'Tonkor', 'Hexaata', 'CambiarEstoPorIdDeAdmin', 'Status Chance', 59.1, 'Damage', 104.0, NULL, NULL, NULL, NULL, 'madurai', 11),
(NEWID(),'Tonkor', 'Magna-lexicron', 'CambiarEstoPorIdDeAdmin', 'Punch Through', 1.2, 'Critical Chance', 71.2, 'Impact Damage', 61.4, NULL, NULL, 'madurai', 11),
(NEWID(),'Tonkor', 'Visicron', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 104.2, 'Damage', 114.9, NULL, NULL, NULL, NULL, 'naramon', 9),
(NEWID(),'Tonkor', 'Acri-Visibin', 'CambiarEstoPorIdDeAdmin', 'Ammo maximum', 34.8, 'Damage', 115.4, 'Critical Damage', 84.5, 'Magazine Capacity', -25.0, 'vazarin', 18),
(NEWID(),'Torid', 'Hexatak', 'CambiarEstoPorIdDeAdmin', 'Status Chance', 136.1, 'Reload Speed', 68.6, NULL, NULL, 'Critical Damage', -64.8, 'madurai', 10),
(NEWID(),'Torid', 'Visi-zetican', 'CambiarEstoPorIdDeAdmin', 'Damage', 138.0, 'Multishot', 69.7, 'Weapon Recoil', -74.4, NULL, NULL, 'madurai', 10),
(NEWID(),'Torid', 'Decitak', 'CambiarEstoPorIdDeAdmin', 'Status Duration', 113.7, 'Reload Speed', 52.4, NULL, NULL, NULL, NULL, 'naramon', 12),
(NEWID(),'Torid', 'Igni-deciata', 'CambiarEstoPorIdDeAdmin', 'Damage', 165.2, 'Heat Damage', 98.4, 'Status Duration', 107.3, 'Status Chance', -84.1, 'vazarin', 10),
(NEWID(),'Torid', 'Ampido', 'CambiarEstoPorIdDeAdmin', 'Ammo maximum', 74.8, 'Cold Damage', 116.0, NULL, NULL, 'Status Duration', -54.9, 'naramon', 15),
(NEWID(),'Torid', 'Ampi-Acridra', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 136.4, 'Ammo maximum', 56.9, 'Fire Rate', 63.8, 'Corpus Damage', -34.8, 'naramon', 18),
(NEWID(),'Torid', 'Igni-cronicron', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 123.3, 'Heat Damage', 76.7, 'Fire Rate', 51.0, NULL, NULL, 'naramon', 11),
(NEWID(),'Torid', 'Igni-vexitak', 'CambiarEstoPorIdDeAdmin', 'Reload Speed', 38.6, 'Heat Damage', 76.8, 'Electric Damage', 73.3, NULL, NULL, 'naramon', 11),
(NEWID(),'Vectis', 'Acricron', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 151.3, 'Critical Damage', 126.3, NULL, NULL, NULL, NULL, 'vazarin', 13),
(NEWID(),'Vectis', 'Lexi-argitron', 'CambiarEstoPorIdDeAdmin', 'Grineer Damage', 32.9, 'Corpus Damage', 31.8, 'Punch Through', 200.0, NULL, NULL, 'naramon', 13),
(NEWID(),'Vectis', 'Gelican', 'CambiarEstoPorIdDeAdmin', 'Multishot', 105.3, 'Cold Damage', 118.5, NULL, NULL, 'Status Chance', -45.8, 'naramon', 10),
(NEWID(),'Vectis', 'Armadra', 'CambiarEstoPorIdDeAdmin', 'Fire Rate', 54.1, 'Magazine Capacity', 50.2, NULL, NULL, NULL, NULL, 'madurai', 11),
(NEWID(),'Vectis', 'Argitox', 'CambiarEstoPorIdDeAdmin', 'Grineer Damage', 47.1, 'Toxin Damage', 81.9, NULL, NULL, NULL, NULL, 'madurai', 11),
(NEWID(),'Vectis', 'Ampicron', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 174.0, 'Ammo maximum', 67.0, 'Magazine Capacity', -26.8, NULL, NULL, 'madurai', 11),
(NEWID(),'Vulkar', 'Toxiata', 'CambiarEstoPorIdDeAdmin', 'Toxin Damage', 163.1, 'Damage', 257.6, NULL, NULL, 'Status Chance', -70.5, 'naramon', 11),
(NEWID(),'Vulkar', 'Vexi-visitox', 'CambiarEstoPorIdDeAdmin', 'Electric Damage', 128.4, 'Damage', 234.4, 'Toxin Damage', 114.7, 'Critical Chance', -158.3, 'vazarin', 12),
(NEWID(),'Vulklok', 'Conci-Acricon', 'CambiarEstoPorIdDeAdmin', 'Grineer Damage', 55.7, 'Critical Chance', 152.1, 'Flight Speed', 115.5, 'Reload Speed', -44.2, 'madurai', 18),
(NEWID(),'Vulklok', 'Gelides', 'CambiarEstoPorIdDeAdmin', 'Cold Damage', 118.8, 'Status Duration', 132.0, NULL, NULL, NULL, NULL, 'vazarin', 18),
(NEWID(),'Zarr', 'Arma-acriton', 'CambiarEstoPorIdDeAdmin', 'Impact Damage', 88.4, 'Critical Damage', 92.1, 'Magazine Capacity', 40.4, NULL, NULL, 'madurai', 9),
(NEWID(),'Zarr', 'Crita-satiata', 'CambiarEstoPorIdDeAdmin', 'Damage', 148.9, 'Critical Chance', 148.3, 'Multishot', 85.4, 'Reload Speed', -34.8, 'madurai', 11),
(NEWID(),'Zarr', 'Lexiton', 'CambiarEstoPorIdDeAdmin', 'Impact Damage', 0.0, 'Punch Through', 0.0, NULL, NULL, 'Slash Damage', 0.0, 'madurai', 11),
(NEWID(),'Zarr', 'Decidex', 'CambiarEstoPorIdDeAdmin', 'Status Chance', 0.0, 'Status Duration', 0.0, NULL, NULL, NULL, NULL, 'madurai', 11),
(NEWID(),'Zarr', 'Argi-zetitox', 'CambiarEstoPorIdDeAdmin', 'Weapon Recoil', -78.0, 'Toxin Damage', 76.2, 'Grineer Damage', 45.4, 'Reload Speed', -36.4, 'naramon', 12),
(NEWID(),'Zarr', 'Ignidex', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 120.5, 'Status Chance', 115.5, NULL, NULL, 'Infested Damage', -21.3, 'vazarin', 15),
(NEWID(),'Zarr', 'Hexa-insicron', 'CambiarEstoPorIdDeAdmin', 'Status Chance', 92.8, 'Critical Chance', 137.9, 'Puncture Damage', 111.8, 'Impact Damage', -89.9, 'naramon', 16),
(NEWID(),'Zarr', 'Igni-insicron', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 128.0, 'Puncture Damage', 109.7, 'Heat Damage', 88.1, 'Zoom', -45.8, 'naramon', 16),
(NEWID(),'Zarr', 'Arma-puraata', 'CambiarEstoPorIdDeAdmin', 'Damage', 111.7, 'Magazine Capacity', 40.9, 'Infested Damage', 35.5, NULL, NULL, 'naramon', 16),
(NEWID(),'Zarr', 'Zeti-critaata', 'CambiarEstoPorIdDeAdmin', 'Damage', 112.4, 'Weapon Recoil', -73.7, 'Critical Chance', 105.7, NULL, NULL, 'madurai', 13),
(NEWID(),'Zarr', 'Visi-concicron', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 128.4, 'Damage', 166.6, 'Flight Speed', 79.9, 'Corpus Damage', -34.7, 'vazarin', 14),
(NEWID(),'Zarr', 'Croni-mantinak', 'CambiarEstoPorIdDeAdmin', 'Flight Speed', 62.5, 'Corpus Damage', 32.6, 'Fire Rate', 45.1, NULL, NULL, 'madurai', 16),
(NEWID(),'Zhuge', 'Vexi-visido', 'CambiarEstoPorIdDeAdmin', 'Electric Damage', 101.8, 'Damage', 185.2, 'Cold Damage', 95.7, 'Ammo maximum', -38.8, 'vazarin', 8),
(NEWID(),'Zhuge', 'Acripha', 'CambiarEstoPorIdDeAdmin', 'Heat Damage', 125.7, 'Critical Damage', 172.7, NULL, NULL, 'Zoom', -32.0, 'madurai', 8),
(NEWID(),'Zhuge', 'Critatox', 'CambiarEstoPorIdDeAdmin', 'Toxin Damage', 126.3, 'Critical Chance', 212.3, NULL, NULL, 'Ammo maximum', -28.6, 'vazarin', 8),
(NEWID(),'Zhuge', 'Vexi-decicak', 'CambiarEstoPorIdDeAdmin', 'Status Duration', 79.0, 'Puncture Damage', 94.5, 'Electric Damage', 74.7, NULL, NULL, 'naramon', 9),
(NEWID(),'Zhuge', 'Fevaata', 'CambiarEstoPorIdDeAdmin', 'Damage', 210.5, 'Reload Speed', 70.4, NULL, NULL, 'Magazine Capacity', -26.1, 'naramon', 10),
(NEWID(),'Zhuge', 'Visicron', 'CambiarEstoPorIdDeAdmin', 'Damage', 244.9, 'Critical Chance', 194.4, NULL, NULL, 'Flight Speed', -51.0, 'madurai', 11),
(NEWID(),'Zhuge', 'Satiata', 'CambiarEstoPorIdDeAdmin', 'Damage', 226.2, 'Multishot', 125.9, NULL, NULL, 'Ammo maximum', -26.0, 'vazarin', 13),
(NEWID(),'Zhuge', 'Acri-cronitio', 'CambiarEstoPorIdDeAdmin', 'Critical Damage', 99.0, 'Electric Damage', 67.7, 'Fire Rate', 48.8, NULL, NULL, 'vazarin', 13),
(NEWID(),'Zhuge', 'Saticron', 'CambiarEstoPorIdDeAdmin', 'Multishot', 99.7, 'Critical Chance', 150.2, NULL, NULL, NULL, NULL, 'naramon', 13),
(NEWID(),'Zhuge', 'Ampi-hexatio', 'CambiarEstoPorIdDeAdmin', 'Electric Damage', 85.3, 'Status Chance', 86.8, 'Ammo maximum', 53.0, 'Damage', -146.4, 'naramon', 14),
(NEWID(),'Zhuge', 'Visipha', 'CambiarEstoPorIdDeAdmin', 'Damage', 175.1, 'Heat Damage', 93.5, NULL, NULL, NULL, NULL, 'naramon', 14),
(NEWID(),'Zhuge', 'Argi-ampicron', 'CambiarEstoPorIdDeAdmin', 'Grineer Damage', 40.1, 'Ammo maximum', 43.2, 'Critical Chance', 116.9, NULL, NULL, 'naramon', 15),
(NEWID(),'Zhuge', 'Sati-ignido', 'CambiarEstoPorIdDeAdmin', 'Multishot', 75.4, 'Cold Damage', 69.9, 'Heat Damage', 70.0, NULL, NULL, 'naramon', 15),
(NEWID(),'Zhuge', 'Sati-argiata', 'CambiarEstoPorIdDeAdmin', 'Damage', 183.1, 'Grineer Damage', 50.3, 'Multishot', 102.1, 'Zoom', -48.3, 'madurai', 15),
(NEWID(),'Zhuge', 'Crita-vexitis', 'CambiarEstoPorIdDeAdmin', 'Electric Damage', 93.1, 'Critical Chance', 162.6, 'Critical Damage', 113.1, 'Zoom', -54.2, 'madurai', 16),
(NEWID(),'Zhuge', 'Toxi-fevacron', 'CambiarEstoPorIdDeAdmin', 'Critical Chance', 164.0, 'Toxin Damage', 99.7, 'Reload Speed', 54.8, 'Zoom', -50.8, 'naramon', 13);