// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarframeRivensAPI.Data;

#nullable disable

namespace WarframeRivensAPI.Migrations
{
    [DbContext(typeof(WarRivenContext))]
    [Migration("20250516201538_DockerSQL")]
    partial class DockerSQL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "9f1426a2-b729-4d30-99ae-b27efad1f1cd",
                            Name = "basic",
                            NormalizedName = "BASIC"
                        },
                        new
                        {
                            Id = "ea2b316f-75fb-4150-a882-e7c99d52f2af",
                            Name = "confirmado",
                            NormalizedName = "CONFIRMADO"
                        },
                        new
                        {
                            Id = "5a3a3046-e2ab-4752-a538-712e9bd59752",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "9f79a04d-78cb-45fc-bec7-3767d5a803e5",
                            RoleId = "9f1426a2-b729-4d30-99ae-b27efad1f1cd"
                        },
                        new
                        {
                            UserId = "356cf89a-c1ac-488c-81eb-f91ae74ec5a9",
                            RoleId = "ea2b316f-75fb-4150-a882-e7c99d52f2af"
                        },
                        new
                        {
                            UserId = "4ca4b1f2-0053-4fa4-890f-4a0a1b4b6f7e",
                            RoleId = "5a3a3046-e2ab-4752-a538-712e9bd59752"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WarframeRivensAPI.Models.Favorito", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdRiven")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RivenId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.HasIndex("RivenId");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("WarframeRivensAPI.Models.Oferta", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Destino")
                        .HasColumnType("bit");

                    b.Property<bool>("Disponibilidad")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdComprador")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdRiven")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Partida")
                        .HasColumnType("bit");

                    b.Property<int>("PrecioVenta")
                        .HasColumnType("int");

                    b.Property<string>("RivenId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdComprador");

                    b.HasIndex("RivenId");

                    b.ToTable("Ofertas");
                });

            modelBuilder.Entity("WarframeRivensAPI.Models.Riven", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Arma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Atrib1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Atrib2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Atrib3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAtrib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DValor")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("IdPropietario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Maestria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Polaridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor1")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal?>("Valor2")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal?>("Valor3")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("WarUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdPropietario");

                    b.HasIndex("WarUserId");

                    b.ToTable("Rivens");
                });

            modelBuilder.Entity("WarframeRivensAPI.Models.Venta", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdComprador")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdRiven")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdVendedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PrecioVenta")
                        .HasColumnType("int");

                    b.Property<string>("RivenId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdComprador");

                    b.HasIndex("IdVendedor");

                    b.HasIndex("RivenId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("WarframeRivensAPI.Models.WarUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Icono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SteamId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("WarframeNick")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "9f79a04d-78cb-45fc-bec7-3767d5a803e5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "99c21530-a053-46a3-ad56-e2d3e3c06388",
                            Email = "visitante@warriven.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "Usuario Visitante",
                            NormalizedEmail = "VISITANTE@WARRIVEN.COM",
                            NormalizedUserName = "VISITANTE@WARRIVEN.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMIdYfOpd6h1RyCwrccvVdXntwDr0Uh6pFWfLkchi3syo7aSekku4T+Z10akSkTn2Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fb0666f0-5022-4cb5-b555-a03e569f9f46",
                            TwoFactorEnabled = false,
                            UserName = "visitante@warriven.com"
                        },
                        new
                        {
                            Id = "356cf89a-c1ac-488c-81eb-f91ae74ec5a9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0a0933cc-310f-4ba4-a4b9-3242c0dad5b9",
                            Email = "confirmado@warriven.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "Usuario confirmado",
                            NormalizedEmail = "CONFIRMADO@WARRIVEN.COM",
                            NormalizedUserName = "CONFIRMADO@WARRIVEN.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOlbGEbi5soF1HG+vC5qrzmLjmHm4QNCR4QUud5ocgt22ZXt9LTAQboCN6waFcX9Tg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a351dc54-f5f9-41d5-9d10-c71ab21fef79",
                            TwoFactorEnabled = false,
                            UserName = "confirmado@warriven.com"
                        },
                        new
                        {
                            Id = "4ca4b1f2-0053-4fa4-890f-4a0a1b4b6f7e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "30ed7f83-7426-4b17-b548-d858bcef2d5f",
                            Email = "admin@warriven.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "Administrador",
                            NormalizedEmail = "ADMIN@WARRIVEN.COM",
                            NormalizedUserName = "ADMIN@WARRIVEN.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFyHRZIXm/Hwvj9tjJR7v4aZUX2WuRUCyqFxBAX5Xx0SbDnflSRmuSwTSWzDPmNXgA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7fd0b839-3d70-4f72-a6f8-4516ccda4999",
                            TwoFactorEnabled = false,
                            UserName = "admin@warriven.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WarframeRivensAPI.Models.WarUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WarframeRivensAPI.Models.WarUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarframeRivensAPI.Models.WarUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WarframeRivensAPI.Models.WarUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarframeRivensAPI.Models.Favorito", b =>
                {
                    b.HasOne("WarframeRivensAPI.Models.WarUser", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarframeRivensAPI.Models.Riven", "Riven")
                        .WithMany()
                        .HasForeignKey("RivenId");

                    b.Navigation("Riven");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WarframeRivensAPI.Models.Oferta", b =>
                {
                    b.HasOne("WarframeRivensAPI.Models.WarUser", "Comprador")
                        .WithMany()
                        .HasForeignKey("IdComprador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarframeRivensAPI.Models.Riven", "Riven")
                        .WithMany()
                        .HasForeignKey("RivenId");

                    b.Navigation("Comprador");

                    b.Navigation("Riven");
                });

            modelBuilder.Entity("WarframeRivensAPI.Models.Riven", b =>
                {
                    b.HasOne("WarframeRivensAPI.Models.WarUser", "Propietario")
                        .WithMany()
                        .HasForeignKey("IdPropietario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarframeRivensAPI.Models.WarUser", null)
                        .WithMany("Rivens")
                        .HasForeignKey("WarUserId");

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("WarframeRivensAPI.Models.Venta", b =>
                {
                    b.HasOne("WarframeRivensAPI.Models.WarUser", "Comprador")
                        .WithMany()
                        .HasForeignKey("IdComprador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarframeRivensAPI.Models.WarUser", "Vendedor")
                        .WithMany()
                        .HasForeignKey("IdVendedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarframeRivensAPI.Models.Riven", "Riven")
                        .WithMany()
                        .HasForeignKey("RivenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Riven");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("WarframeRivensAPI.Models.WarUser", b =>
                {
                    b.Navigation("Rivens");
                });
#pragma warning restore 612, 618
        }
    }
}
